// ─── MATERIAL LEAF PAGE DATA ───
// Per Content Rules: 800-1,500 words per leaf page. Narrower scope, unique depth.

export type MaterialLeafData = {
  parentSlug: string;
  parentName: string;
  slug: string;     // full path after /materials/ e.g. 'electronics/cell-phones'
  name: string;
  definition: string;
  acceptedItems: string[];
  hasDataSecurity: boolean;
  dataSecurity?: string;
  process: { title: string; description: string }[];
  siblings: { slug: string; name: string }[];
  services: { slug: string; name: string }[];
  faqs: { q: string; a: string }[];
  titleTag: string;
  metaDescription: string;
};

export const MATERIAL_LEAF_PAGES: Record<string, MaterialLeafData> = {
  // ─── METALS ───
  'metals/ferrous-metals': {
    parentSlug: 'metals', parentName: 'Scrap Metal', slug: 'metals/ferrous-metals', name: 'Ferrous Metals',
    definition: 'Ferrous metals contain iron and are magnetic — including steel, cast iron, and wrought iron. They make up the bulk of commercial scrap metal by weight and are 100% recyclable into new steel products.',
    acceptedItems: ['Structural steel beams and plates', 'Cast iron pipes, grates, and engine blocks', 'Wrought iron fencing and railings', 'Sheet metal and ductwork', 'Rebar and wire mesh', 'Steel drums and containers', 'Auto body panels and frames', 'Industrial machinery and equipment'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'Picked up via roll-off, flatbed, or grapple truck depending on volume and form.' },
      { title: 'Sorting', description: 'Separated from non-ferrous metals using magnets. Graded by type and quality.' },
      { title: 'Processing', description: 'Sheared, shredded, or baled depending on the form. Prepared for mill specifications.' },
      { title: 'Melting', description: 'Shipped to domestic steel mills where it\'s melted in electric arc furnaces and formed into new steel products.' },
    ],
    siblings: [
      { slug: 'metals/non-ferrous-metals/copper', name: 'Copper' },
      { slug: 'metals/non-ferrous-metals/aluminum', name: 'Aluminum' },
      { slug: 'metals/non-ferrous-metals/brass', name: 'Brass' },
      { slug: 'metals/stainless-steel', name: 'Stainless Steel' },
    ],
    services: [{ slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling' }, { slug: 'dumpster-rental', name: 'Dumpster Rental' }],
    faqs: [
      { q: 'How do I know if my scrap is ferrous?', a: 'If a magnet sticks to it, it\'s ferrous. Steel, cast iron, and wrought iron are all ferrous. Stainless steel is technically ferrous but is priced and processed separately due to its alloy content.' },
      { q: 'What\'s ferrous scrap worth?', a: 'Ferrous scrap prices follow the steel commodity market. Rates are lower per pound than non-ferrous metals but ferrous is accepted in much larger volumes. Current rates depend on grade, form, and market conditions.' },
      { q: 'Do you pick up ferrous scrap for free?', a: 'For commercial volumes (1+ ton), yes. Ferrous scrap has commodity value — we haul it and pay you based on weight and grade.' },
      { q: 'What\'s the difference between #1 and #2 steel?', a: '#1 Heavy Melt is clean, thick steel (1/4 inch+) without attachments. #2 is thinner steel, mixed grades, or steel with some attachments. #1 commands a higher price per ton.' },
      { q: 'Can painted or rusted steel be recycled?', a: 'Yes. Paint, rust, and light coatings burn off during the melting process. Heavily contaminated steel (chemical, oil) may require separate handling.' },
    ],
    titleTag: 'Ferrous Metal Recycling — Steel, Iron & Cast Iron',
    metaDescription: 'Recycle ferrous metals including steel, cast iron, and wrought iron. Free commercial pickup. Competitive pricing. 97+ cities. 817-946-5655.',
  },
  'metals/non-ferrous-metals/copper': {
    parentSlug: 'metals', parentName: 'Scrap Metal', slug: 'metals/non-ferrous-metals/copper', name: 'Copper',
    definition: 'Copper is one of the most valuable recyclable metals, commonly found in electrical wiring, plumbing pipe, HVAC components, and industrial equipment. Recycled copper retains 100% of its properties and is worth $3-$4+ per pound depending on grade.',
    acceptedItems: ['Bare bright copper wire (#1)', 'Insulated copper wire (#2)', 'Copper pipe and tubing', 'Copper sheet and plate', 'Copper bus bars and windings', 'HVAC copper coils and line sets', 'Copper fittings and valves', 'Copper turnings and grindings'],
    hasDataSecurity: false,
    process: [
      { title: 'Grading', description: 'Copper is graded: #1 Bare Bright (highest — clean, uncoated wire), #1 Copper (clean pipe/sheet), #2 (painted, soldered, or with attachments).' },
      { title: 'Stripping', description: 'Insulated wire is stripped to recover bare copper. Thickness and insulation type determine whether mechanical or manual stripping is used.' },
      { title: 'Melting', description: 'Clean copper is melted at domestic refineries and cast into new copper rod, sheet, or tube for manufacturing.' },
    ],
    siblings: [
      { slug: 'metals/ferrous-metals', name: 'Ferrous Metals' },
      { slug: 'metals/non-ferrous-metals/aluminum', name: 'Aluminum' },
      { slug: 'metals/non-ferrous-metals/brass', name: 'Brass' },
      { slug: 'metals/stainless-steel', name: 'Stainless Steel' },
    ],
    services: [{ slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling' }],
    faqs: [
      { q: 'What\'s copper worth per pound?', a: 'Bare bright copper (#1) typically ranges $3-$4+/lb depending on COMEX copper prices. Insulated wire pays less because stripping is required. We quote at current daily rates.' },
      { q: 'What\'s the difference between #1 and #2 copper?', a: '#1 is clean, uncoated, unsoldered copper — bare bright wire or clean pipe. #2 has paint, solder, fittings, or light contamination. The price difference is typically $0.50-$1.00/lb.' },
      { q: 'Do you buy insulated copper wire?', a: 'Yes. Price depends on copper recovery rate — thicker insulated wire (like Romex) pays more than thin communication cable. We can strip at our facility or buy as-is at insulated rates.' },
      { q: 'Is there a minimum for copper pickup?', a: 'For copper and other non-ferrous metals, we generally pick up at 200+ lbs. Smaller quantities can be dropped off at our partner yards.' },
      { q: 'Can I recycle copper pipe with solder joints?', a: 'Yes — it grades as #2 copper. Clean pipe without solder or fittings grades as #1. Removing fittings before bringing it in maximizes your price.' },
    ],
    titleTag: 'Copper Recycling — Wire, Pipe, Sheet & Scrap',
    metaDescription: 'Recycle copper wire, pipe, and scrap at competitive daily rates. #1 and #2 copper accepted. Free commercial pickup. 97+ cities. 817-946-5655.',
  },
  'metals/non-ferrous-metals/aluminum': {
    parentSlug: 'metals', parentName: 'Scrap Metal', slug: 'metals/non-ferrous-metals/aluminum', name: 'Aluminum',
    definition: 'Aluminum recycling recovers one of the most energy-efficient recyclable materials — recycling aluminum uses 95% less energy than producing it from raw bauxite ore. Common sources include extrusions, sheet, cans, castings, and automotive parts.',
    acceptedItems: ['Aluminum extrusions (window frames, structural)', 'Aluminum sheet and plate', 'Aluminum cans (UBC)', 'Cast aluminum (engine parts, wheels)', 'Aluminum siding and gutters', 'Aluminum wire and cable', 'Aluminum turnings and chips', 'Lithographic aluminum plates'],
    hasDataSecurity: false,
    process: [
      { title: 'Sorting', description: 'Separated by alloy series (1000-7000). Different alloys have different values and processing requirements.' },
      { title: 'Cleaning', description: 'Paint, coatings, and attachments removed. Clean aluminum commands better rates.' },
      { title: 'Melting', description: 'Melted at 1,220°F — significantly lower than the 3,700°F needed to process raw bauxite. This energy savings is why aluminum recycling is so economically favorable.' },
    ],
    siblings: [
      { slug: 'metals/ferrous-metals', name: 'Ferrous Metals' },
      { slug: 'metals/non-ferrous-metals/copper', name: 'Copper' },
      { slug: 'metals/non-ferrous-metals/brass', name: 'Brass' },
      { slug: 'metals/stainless-steel', name: 'Stainless Steel' },
    ],
    services: [{ slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling' }],
    faqs: [
      { q: 'What\'s aluminum scrap worth?', a: 'Pricing varies by alloy and form. Clean extrusions and sheet typically pay $0.50-$1.00+/lb. Cast aluminum pays less. UBC (used beverage cans) have their own market rate. We quote at daily commodity prices.' },
      { q: 'Why is aluminum recycling so energy-efficient?', a: 'Producing aluminum from raw bauxite ore requires massive amounts of electricity for smelting. Recycling skips the smelting step — melting existing aluminum uses 95% less energy. This makes aluminum one of the most economically and environmentally favorable materials to recycle.' },
      { q: 'Do you accept aluminum cans?', a: 'Yes, in commercial quantities. Used Beverage Cans (UBC) are one of the most recycled products in the world. For businesses generating large volumes (restaurants, venues, cafeterias), we provide dedicated collection.' },
      { q: 'Can painted aluminum be recycled?', a: 'Yes. Paint burns off during melting. However, clean aluminum (no paint, no attachments) grades higher and pays more.' },
      { q: 'What about aluminum wheels and automotive parts?', a: 'Cast aluminum from wheels, engine components, and transmission housings is accepted. These are alloy-specific and priced accordingly — typically slightly less than wrought/sheet aluminum.' },
    ],
    titleTag: 'Aluminum Recycling — Extrusions, Sheet, Cans & Castings',
    metaDescription: 'Recycle aluminum scrap at competitive prices. Extrusions, sheet, cans, castings. 95% energy savings vs virgin production. 97+ cities. 817-946-5655.',
  },
  'metals/non-ferrous-metals/brass': {
    parentSlug: 'metals', parentName: 'Scrap Metal', slug: 'metals/non-ferrous-metals/brass', name: 'Brass',
    definition: 'Brass is a copper-zinc alloy commonly found in plumbing fittings, valves, door hardware, decorative fixtures, and ammunition casings. It\'s one of the higher-value scrap metals due to its copper content.',
    acceptedItems: ['Plumbing fittings and valves', 'Door handles, hinges, and hardware', 'Brass pipe and rod', 'Shell casings and ammunition brass', 'Musical instruments', 'Decorative fixtures and trim', 'Brass turnings and chips'],
    hasDataSecurity: false,
    process: [
      { title: 'Sorting', description: 'Separated from other metals and graded: yellow brass, red brass, and semi-red brass based on copper content.' },
      { title: 'Cleaning', description: 'Steel attachments (screws, springs) removed. Clean brass commands the best rates.' },
      { title: 'Melting', description: 'Melted and re-alloyed at domestic foundries for new brass products.' },
    ],
    siblings: [
      { slug: 'metals/ferrous-metals', name: 'Ferrous Metals' },
      { slug: 'metals/non-ferrous-metals/copper', name: 'Copper' },
      { slug: 'metals/non-ferrous-metals/aluminum', name: 'Aluminum' },
      { slug: 'metals/stainless-steel', name: 'Stainless Steel' },
    ],
    services: [{ slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling' }],
    faqs: [
      { q: 'What\'s brass worth?', a: 'Yellow brass (most common) typically pays $1.50-$2.50/lb. Red brass (higher copper content) pays more. Pricing follows copper commodity markets since brass is primarily a copper alloy.' },
      { q: 'What\'s the difference between yellow and red brass?', a: 'Yellow brass is ~60-70% copper, ~30-40% zinc — most fittings and hardware. Red brass is ~85% copper, ~15% zinc — found in valves, water meters, and some plumbing. Red brass pays more due to higher copper content.' },
      { q: 'Do you accept shell casings?', a: 'Yes. Spent brass shell casings are a common and valuable brass scrap source. We accept all calibers in commercial quantities.' },
      { q: 'Can brass with steel attachments be recycled?', a: 'Yes, but it grades lower. Removing steel screws, springs, and other attachments before recycling results in a cleaner grade and better price.' },
    ],
    titleTag: 'Brass Recycling — Fittings, Valves, Hardware & Casings',
    metaDescription: 'Recycle brass scrap including fittings, valves, door hardware, and shell casings. Competitive pricing on yellow and red brass. 817-946-5655.',
  },
  'metals/stainless-steel': {
    parentSlug: 'metals', parentName: 'Scrap Metal', slug: 'metals/stainless-steel', name: 'Stainless Steel',
    definition: 'Stainless steel is a corrosion-resistant alloy containing iron, chromium (10.5%+), and often nickel. Common grades include 304 (food equipment, sinks) and 316 (marine, medical). It\'s more valuable than carbon steel due to its alloy content.',
    acceptedItems: ['304 stainless (food equipment, countertops, sinks)', '316 stainless (marine, medical, chemical)', 'Stainless pipe, tube, and fittings', 'Stainless sheet and plate', 'Restaurant and food service equipment', 'Medical and surgical instruments', 'Stainless turnings and chips'],
    hasDataSecurity: false,
    process: [
      { title: 'Testing', description: 'Grade determined by XRF analysis — different grades (304, 316, 430, etc.) have different values based on nickel and chromium content.' },
      { title: 'Sorting', description: 'Separated by grade. Mixing grades reduces value. Clean, sorted stainless earns premium pricing.' },
      { title: 'Melting', description: 'Processed at specialty stainless steel mills using electric arc furnaces. Alloy content is preserved in the recycled product.' },
    ],
    siblings: [
      { slug: 'metals/ferrous-metals', name: 'Ferrous Metals' },
      { slug: 'metals/non-ferrous-metals/copper', name: 'Copper' },
      { slug: 'metals/non-ferrous-metals/aluminum', name: 'Aluminum' },
      { slug: 'metals/non-ferrous-metals/brass', name: 'Brass' },
    ],
    services: [{ slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling' }],
    faqs: [
      { q: 'How much is stainless steel worth?', a: '304 stainless typically pays $0.40-$0.80/lb. 316 pays more ($0.60-$1.20/lb) due to higher nickel content. Prices follow the nickel commodity market. We verify grade with XRF testing for accurate pricing.' },
      { q: 'How do you determine stainless steel grade?', a: 'We use handheld XRF (X-ray fluorescence) analyzers to determine exact alloy composition. This ensures accurate grading and fair pricing — no guessing based on appearance.' },
      { q: 'Is magnetic stainless steel still stainless?', a: 'Some stainless grades (like 430) are magnetic. Others (304, 316) are typically non-magnetic but can become slightly magnetic after cold working. XRF testing confirms grade regardless of magnetic properties.' },
      { q: 'Do you pick up restaurant equipment?', a: 'Yes. Stainless steel prep tables, sinks, hoods, and walk-in components from restaurant decommissions. We haul and pay by weight at the appropriate grade.' },
    ],
    titleTag: 'Stainless Steel Recycling — 304, 316 & All Grades',
    metaDescription: 'Recycle stainless steel scrap — 304, 316, and all grades. XRF grade verification for accurate pricing. Free commercial pickup. 817-946-5655.',
  },
  'metals/steel': {
    parentSlug: 'metals', parentName: 'Scrap Metal', slug: 'metals/steel', name: 'Steel & Iron',
    definition: 'Steel and iron scrap recycling processes the highest-volume category of recyclable metal — structural steel, car bodies, cast iron, motor blocks, sheet metal, and industrial scrap. Steel is 100% recyclable and can be remelted indefinitely without losing strength, making it the backbone of the circular metals economy.',
    acceptedItems: ['Clean Motor Block Scrap', 'Flattened Scrap Car Bodies', 'Mixed Cast Iron Scrap', 'Mixed Scrap Iron & Steel', 'No.1 Steel Scrap (2 foot)', 'No.1 Steel Scrap (HMS1)', 'No.2 Steel Scrap', 'No.2 Steel Scrap (2 foot)', 'No.3 Steel Scrap (Unprepared Bushling)', 'No.4 Shredded Steel Scrap', 'Other Scrap Iron & Steel', 'Scrap Steel Wheel Rims', 'Sheet Iron Scrap (Sheet Tin)', 'Sorted Machine Cast Scrap', 'Sorted Scrap Automotive Cast', 'Unclean Motor Block Scrap', 'Whole Prepared Scrap Car Bodies'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'Picked up via roll-off containers, flatbeds, or grapple trucks depending on volume and form factor. Heavy structural steel may require crane loading.' },
      { title: 'Grading', description: 'Steel graded by ISRI specifications: No.1 Heavy Melt (HMS1) is the premium grade (clean, 1/4\"+). No.2 is thinner or mixed. Shredded, cast, and automotive scrap each have separate grades.' },
      { title: 'Processing', description: 'Sheared to mill-ready dimensions, shredded for density, or baled for transport. Torch cutting for oversized pieces. Non-ferrous attachments removed.' },
      { title: 'Melting', description: 'Shipped to domestic steel mills where it\'s melted in electric arc furnaces at 3,000°F and formed into new steel products — rebar, beams, sheet, wire.' },
    ],
    siblings: [
      { slug: 'metals/non-ferrous-metals/copper', name: 'Copper' },
      { slug: 'metals/non-ferrous-metals/aluminum', name: 'Aluminum' },
      { slug: 'metals/non-ferrous-metals/brass', name: 'Brass' },
      { slug: 'metals/stainless-steel', name: 'Stainless Steel' },
      { slug: 'metals/lead', name: 'Lead' },
      { slug: 'metals/ferrous-metals', name: 'Other Ferrous Metals' },
    ],
    services: [{ slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling' }, { slug: 'dumpster-rental', name: 'Dumpster Rental' }],
    faqs: [
      { q: 'What\'s the difference between No.1 and No.2 steel scrap?', a: 'No.1 Heavy Melt Steel (HMS1) is clean steel at least 1/4" thick, no more than 5\' in any dimension, free of attachments. No.2 is thinner, may have light attachments, or is mixed grade. HMS1 commands a premium because it requires less processing before melting.' },
      { q: 'How much is steel scrap worth?', a: 'Steel scrap prices follow commodity markets and fluctuate with demand. HMS1 typically pays more per ton than No.2 or shredded. Automotive cast and motor blocks have their own rate schedules. We pay at current daily market rates based on grade.' },
      { q: 'Do you accept whole cars for scrap?', a: 'Yes. Whole prepared car bodies (fluids drained, tires removed) and flattened car bodies are both accepted. Price is based on weight at ferrous scrap rates. Title required for whole vehicles.' },
      { q: 'What about cast iron?', a: 'Cast iron (engine blocks, pipes, grates, machine bases) is accepted and priced at cast iron rates — typically slightly different from steel rates. Mixed cast iron scrap and sorted machine cast scrap are separate grades.' },
      { q: 'Is there a minimum weight for steel pickup?', a: 'For free commercial pickup, we typically require 2+ tons of steel scrap. Smaller quantities can be dropped off at partner yards. For ongoing generators, we place containers at your facility for accumulation between scheduled pickups.' },
      { q: 'What about sheet metal and tin?', a: 'Sheet iron scrap (sheet tin) — including tin cans, roofing tin, HVAC ductwork, and light gauge steel — is accepted at light iron rates. Baling increases value by reducing transportation cost per ton.' },
    ],
    titleTag: 'Steel & Iron Scrap Recycling — HMS1, Cast Iron, Car Bodies & More',
    metaDescription: 'Recycle steel and iron scrap at competitive rates. HMS1, cast iron, car bodies, motor blocks, structural steel. Free pickup at 2+ tons. 817-946-5655.',
  },
  'metals/lead': {
    parentSlug: 'metals', parentName: 'Scrap Metal', slug: 'metals/lead', name: 'Lead',
    definition: 'Lead recycling recovers one of the most recycled metals in the world — primarily from lead-acid batteries, but also from solder, cable sheathing, roofing, radiation shielding, and industrial applications. Lead is classified as a toxic metal under EPA regulations, requiring licensed handling and documented disposal.',
    acceptedItems: ['Lead Dross', 'Lead Solder Scrap', 'Mixed Scrap Lead', 'Scrap Battery Lugs', 'Scrap Lead Battery Plates', 'Lead cable sheathing', 'Lead sheet and pipe (roofing, plumbing)', 'Lead wheel weights', 'Lead radiation shielding', 'Lead type (printing)', 'Lead shot and bullets'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'Lead scrap collected in lined containers to prevent soil contamination. DOT-compliant packaging for transport. Lead-acid batteries collected separately.' },
      { title: 'Classification', description: 'Sorted by type: soft lead (pure), hard lead (antimonial), battery lead (plates and lugs), dross, and mixed. Each type has different value and processing requirements.' },
      { title: 'Smelting', description: 'Processed at secondary lead smelters where lead is melted, refined, and recast into ingots. Recovery rate exceeds 99% for clean lead scrap.' },
      { title: 'Battery Processing', description: 'Lead-acid batteries are the primary source: lead plates and grids are smelted, sulfuric acid is neutralized or recycled, polypropylene cases are recycled into new battery cases.' },
    ],
    siblings: [
      { slug: 'metals/steel', name: 'Steel & Iron' },
      { slug: 'metals/non-ferrous-metals/copper', name: 'Copper' },
      { slug: 'metals/non-ferrous-metals/aluminum', name: 'Aluminum' },
      { slug: 'metals/non-ferrous-metals/brass', name: 'Brass' },
      { slug: 'metals/stainless-steel', name: 'Stainless Steel' },
    ],
    services: [{ slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling' }, { slug: 'hazardous-waste-disposal', name: 'Hazardous Waste Disposal' }],
    faqs: [
      { q: 'Is lead scrap hazardous waste?', a: 'Lead is a toxic metal regulated under EPA RCRA. Lead scrap that fails the TCLP test (leaches lead above 5.0 mg/L) is classified as hazardous waste. Lead-acid batteries are classified as universal waste with simplified handling rules. We manage the classification and compliance requirements.' },
      { q: 'How much is lead scrap worth?', a: 'Lead prices follow the LME (London Metal Exchange). Clean soft lead typically pays $0.40-$0.70/lb depending on market conditions. Battery plates and lugs are priced based on lead content and contamination level.' },
      { q: 'Do you accept lead-acid batteries?', a: 'Yes — lead-acid batteries are the most commonly recycled lead source. Automotive, UPS, forklift, and industrial batteries all accepted. Nearly 99% of a lead-acid battery is recyclable. See also our batteries page for all battery types.' },
      { q: 'What about lead solder and dross?', a: 'Lead solder scrap and lead dross from manufacturing are accepted. Dross (the oxidized material skimmed from molten lead) has lower lead content but is still recoverable. Priced based on lead percentage.' },
      { q: 'Are there handling requirements for lead scrap?', a: 'Yes. Lead scrap should be stored to prevent soil and water contamination — lined containers or sealed drums. Workers handling lead should follow OSHA lead standards (29 CFR 1910.1025). We provide compliant containers and coordinate licensed transport.' },
    ],
    titleTag: 'Lead Recycling — Batteries, Solder, Dross & Scrap Lead',
    metaDescription: 'Recycle lead scrap: battery plates, solder, dross, cable sheathing, sheet lead. EPA compliant handling. Licensed transport. 817-946-5655.',
  },

  // ─── ELECTRONICS ───
  'electronics/cell-phones': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/cell-phones', name: 'Cell Phones & Mobile Devices',
    definition: 'Cell phone recycling recovers precious metals (gold, silver, palladium), rare earth elements, and base metals from smartphones, tablets, and mobile devices while ensuring certified data destruction on all storage media.',
    acceptedItems: ['iPhones (all models and conditions)', 'Samsung Galaxy, Note, and Fold series', 'Google Pixel phones', 'iPads and Android tablets', 'Smartwatches (Apple Watch, Samsung, Fitbit)', 'Feature phones and flip phones', 'E-readers (Kindle, Nook)', 'Mobile hotspots and cellular modems'],
    hasDataSecurity: true,
    dataSecurity: 'All mobile devices undergo NIST 800-88 compliant data destruction before material recovery. Factory reset alone is NOT sufficient — forensic tools can recover data from factory-reset devices. We perform certified wiping or physical shredding depending on device type and your security requirements. Certificate of Destruction issued per device.',
    process: [
      { title: 'Data Destruction', description: 'NIST 800-88 compliant wipe or physical shred. COD per device with serial/IMEI number.' },
      { title: 'Testing', description: 'Devices tested for refurbishment potential. Working devices with market value are remarketed — revenue returned to you.' },
      { title: 'Dismantling', description: 'Non-reusable devices dismantled: batteries removed for separate recycling, circuit boards sent to precious metal refiners, screens and housings sorted by material.' },
      { title: 'Recovery', description: 'Gold, silver, palladium, and copper recovered from circuit boards. Lithium batteries recycled for cobalt and lithium. Glass and aluminum housings recycled.' },
    ],
    siblings: [
      { slug: 'electronics/computers-laptops', name: 'Computers & Laptops' },
      { slug: 'electronics/circuit-boards', name: 'Circuit Boards' },
      { slug: 'electronics/wires-cables', name: 'Wires & Cables' },
      { slug: 'electronics/monitors-tvs', name: 'Monitors & TVs' },
      { slug: 'electronics/printers-copiers', name: 'Printers & Copiers' },
    ],
    services: [{ slug: 'electronics-recycling', name: 'Electronics Recycling' }, { slug: 'data-destruction', name: 'Data Destruction' }, { slug: 'take-back-programs', name: 'Take Back Programs' }],
    faqs: [
      { q: 'Does factory reset destroy data on a phone?', a: 'No. Factory reset removes the file system index but data remains recoverable with forensic tools. NIST 800-88 compliant wiping or physical shredding is required for actual data destruction.' },
      { q: 'Can broken phones be recycled?', a: 'Yes. Cracked screens, water damage, non-functional devices — all accepted. Even non-working phones contain gold, silver, palladium, copper, and lithium worth recovering.' },
      { q: 'Do you pay for old phones?', a: 'Working phones with market value (recent iPhones, Samsung flagships) may qualify for buyback. Older and non-working devices are recycled at no cost. We assess value as part of the intake process.' },
      { q: 'How are lithium batteries handled?', a: 'Phone batteries are removed and recycled separately through licensed battery processors. Lithium-ion batteries are classified as universal waste and require DOT-compliant packaging for transport.' },
      { q: 'Can you handle bulk phone recycling for a company?', a: 'Yes. We process fleet-scale mobile device retirements with NIST 800-88 data destruction, serial/IMEI tracking, and per-device Certificates of Destruction. Common for annual device refresh programs.' },
    ],
    titleTag: 'Cell Phone Recycling — iPhones, Samsung, Tablets & More',
    metaDescription: 'Recycle cell phones and mobile devices with certified data destruction. iPhones, Samsung, tablets, smartwatches. All brands, any condition. 817-946-5655.',
  },
  'electronics/computers-laptops': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/computers-laptops', name: 'Computers & Laptops',
    definition: 'Computer and laptop recycling recovers valuable materials from desktop PCs, laptops, Chromebooks, and workstations while ensuring NIST 800-88 compliant destruction of all data on hard drives and SSDs.',
    acceptedItems: ['Desktop PCs and towers (Dell, HP, Lenovo, etc.)', 'Laptops and notebooks (all brands)', 'Chromebooks (Google, HP, Lenovo, Acer)', 'Mac desktops (iMac, Mac Pro, Mac Mini)', 'MacBooks (all models)', 'Workstations (Dell Precision, HP Z-series)', 'All-in-one computers', 'Thin clients and terminals'],
    hasDataSecurity: true,
    dataSecurity: 'Every computer and laptop contains a hard drive or SSD with potentially sensitive data. We remove and destroy all storage media per NIST 800-88 before any material recovery begins. Methods: software overwrite (for drives being redeployed), degaussing (HDDs only), or physical shredding (SSDs and highest security). Certificate of Destruction per drive with serial number.',
    process: [
      { title: 'Inventory', description: 'Each device cataloged by serial, make, and model. Asset tags recorded for your disposition report.' },
      { title: 'Data Destruction', description: 'All drives removed and destroyed per NIST 800-88. COD per drive.' },
      { title: 'Remarketing', description: 'Recent-model devices with market value are tested, refurbished, and resold. Revenue returned to you.' },
      { title: 'Recycling', description: 'Non-reusable devices dismantled: circuit boards to precious metal refiners, metals to smelters, plastics sorted by resin.' },
    ],
    siblings: [
      { slug: 'electronics/cell-phones', name: 'Cell Phones' },
      { slug: 'electronics/circuit-boards', name: 'Circuit Boards' },
      { slug: 'electronics/wires-cables', name: 'Wires & Cables' },
      { slug: 'electronics/monitors-tvs', name: 'Monitors & TVs' },
      { slug: 'electronics/printers-copiers', name: 'Printers & Copiers' },
    ],
    services: [{ slug: 'it-asset-disposition', name: 'IT Asset Disposition' }, { slug: 'data-destruction', name: 'Data Destruction' }, { slug: 'electronics-recycling', name: 'Electronics Recycling' }],
    faqs: [
      { q: 'Is there a cost to recycle computers?', a: 'Standard desktop and laptop recycling is typically free for commercial quantities. Devices with remarketing value may generate revenue for you. We provide a quote based on your equipment list.' },
      { q: 'Do you track individual devices by serial number?', a: 'Yes. Every device is logged by serial number, make, model, and asset tag. Your asset disposition report provides a complete audit trail from decommission through final processing.' },
      { q: 'Can we get money for old computers?', a: 'Recent-model business laptops (1-4 years old), enterprise servers, and high-end workstations often have remarketing value. We test, refurbish, and resell through our channels — net revenue returned to you.' },
      { q: 'What about Chromebook fleet recycling for schools?', a: 'We specialize in fleet-scale Chromebook disposition. Data destruction on every device, serial-number tracking, FERPA-compliant documentation. Districts typically process 3,000-10,000+ devices per cycle.' },
      { q: 'How quickly can you process a large batch?', a: 'Typical turnaround: 500 devices in 1 week, 2,000 in 2-3 weeks. Expedited processing available for time-sensitive decommissions.' },
    ],
    titleTag: 'Computer & Laptop Recycling — Desktops, Laptops & Chromebooks',
    metaDescription: 'Recycle computers and laptops with NIST 800-88 data destruction. All brands, serial tracking, asset recovery. Free for businesses. 817-946-5655.',
  },
  'electronics/circuit-boards': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/circuit-boards', name: 'Circuit Boards',
    definition: 'Circuit board recycling recovers precious metals — gold, silver, palladium, platinum, and copper — from printed circuit boards (PCBs), motherboards, and electronic components. A ton of circuit boards contains more gold than a ton of gold ore.',
    acceptedItems: ['Computer motherboards', 'Server and networking boards', 'Cell phone circuit boards', 'Telecom and switching equipment boards', 'Military and aerospace boards', 'RAM and memory modules', 'CPU processors', 'Mixed low-grade boards (power supplies, etc.)'],
    hasDataSecurity: false,
    process: [
      { title: 'Grading', description: 'Boards graded: high-grade (telecom, server, military), mid-grade (desktop, laptop), low-grade (power supplies, consumer electronics). Price varies significantly by grade.' },
      { title: 'Shredding', description: 'Boards shredded to liberate components and increase surface area for processing.' },
      { title: 'Refining', description: 'Precious metals extracted through smelting and chemical refining at licensed precious metal refiners. Gold, silver, palladium, platinum, and copper recovered.' },
    ],
    siblings: [
      { slug: 'electronics/cell-phones', name: 'Cell Phones' },
      { slug: 'electronics/computers-laptops', name: 'Computers & Laptops' },
      { slug: 'electronics/wires-cables', name: 'Wires & Cables' },
      { slug: 'electronics/monitors-tvs', name: 'Monitors & TVs' },
    ],
    services: [{ slug: 'electronics-recycling', name: 'Electronics Recycling' }, { slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling' }],
    faqs: [
      { q: 'How much gold is in circuit boards?', a: 'High-grade boards (servers, telecom) contain 5-15+ grams of gold per ton. Consumer-grade boards contain 1-5 grams per ton. The gold is in connectors, IC pins, and plating. At $2,000+/oz, even small concentrations have value.' },
      { q: 'What\'s the difference between high-grade and low-grade boards?', a: 'High-grade boards (servers, telecom, military) have more gold, silver, and palladium content. Low-grade boards (power supplies, consumer electronics) have less precious metal but still have copper value. We pay based on grade.' },
      { q: 'Do you accept loose components like CPUs and RAM?', a: 'Yes. CPUs (especially older ceramic processors) and RAM modules have high precious metal content and are priced accordingly.' },
      { q: 'Is there a minimum quantity?', a: 'For commercial quantities (50+ lbs), we provide free pickup. Smaller quantities can be shipped or dropped off.' },
    ],
    titleTag: 'Circuit Board Recycling — Precious Metal Recovery from PCBs',
    metaDescription: 'Recycle circuit boards for gold, silver, palladium, and copper recovery. Motherboards, server boards, CPUs, RAM. Commercial quantities. 817-946-5655.',
  },
  'electronics/wires-cables': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/wires-cables', name: 'Wires & Cables',
    definition: 'Wire and cable recycling recovers copper and aluminum from insulated electrical wiring, network cables, and power cords through stripping and chopping processes that separate metal conductors from plastic insulation.',
    acceptedItems: ['Copper building wire (Romex, THHN)', 'Cat5/Cat6 network cables', 'Coaxial cable', 'Power cords and extension cords', 'Copper communication cable', 'Aluminum wire and cable', 'XLPE and high-voltage cable', 'Mixed wire and cable scrap'],
    hasDataSecurity: false,
    process: [
      { title: 'Sorting', description: 'Sorted by type: copper vs aluminum, heavy insulation vs thin insulation, single conductor vs multi-conductor.' },
      { title: 'Chopping/Stripping', description: 'Wire fed through granulators that chop and separate copper/aluminum from insulation using gravity separation and air classification.' },
      { title: 'Recovery', description: 'Clean copper and aluminum sold to domestic mills. Insulation (PVC, PE, rubber) recycled where possible or sent to energy recovery.' },
    ],
    siblings: [
      { slug: 'electronics/cell-phones', name: 'Cell Phones' },
      { slug: 'electronics/computers-laptops', name: 'Computers & Laptops' },
      { slug: 'electronics/circuit-boards', name: 'Circuit Boards' },
    ],
    services: [{ slug: 'electronics-recycling', name: 'Electronics Recycling' }, { slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling' }],
    faqs: [
      { q: 'How is insulated wire priced?', a: 'Based on copper recovery rate — the percentage of copper vs insulation by weight. Heavy-gauge building wire (60-70% copper) pays more than thin communication cable (20-30% copper). We can strip or chop at our facility.' },
      { q: 'Should I strip wire before recycling?', a: 'For heavy-gauge wire (#4 and larger), stripping to bare copper significantly increases value. For thin wire, the labor cost of manual stripping exceeds the value gained — sell it insulated and we\'ll process it mechanically.' },
      { q: 'Do you accept aluminum wire?', a: 'Yes. Aluminum wire is priced separately from copper. Clean aluminum building wire is accepted in commercial quantities.' },
      { q: 'What about data/network cable from office decommissions?', a: 'Yes. Cat5, Cat6, and fiber optic cable from office and data center decommissions. Copper content from data cables has value. We handle bulk removal as part of IT decommission projects.' },
    ],
    titleTag: 'Wire & Cable Recycling — Copper Recovery from Insulated Wire',
    metaDescription: 'Recycle insulated copper wire, network cables, and power cords. Copper and aluminum recovery. Commercial quantities. 97+ cities. 817-946-5655.',
  },
  'electronics/monitors-tvs': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/monitors-tvs', name: 'Monitors & TVs',
    definition: 'Monitor and TV recycling handles LCD, LED, and CRT displays, recovering glass, metals, and plastics while safely managing hazardous components like CRT lead glass and LCD mercury backlights.',
    acceptedItems: ['LCD monitors (all sizes)', 'LED monitors and displays', 'CRT monitors and TVs', 'Flat panel TVs (plasma, LCD, LED, OLED)', 'Digital signage and commercial displays', 'All-in-one computer displays', 'Touch screen displays and kiosks', 'Projection equipment'],
    hasDataSecurity: false,
    process: [
      { title: 'Type Sorting', description: 'Separated by technology: CRT (requires lead glass handling), LCD (requires mercury backlight handling), LED (standard recycling).' },
      { title: 'Hazmat Removal', description: 'CRTs: lead-containing funnel glass separated from panel glass. LCD: mercury-containing backlights removed for proper hazardous waste disposal.' },
      { title: 'Material Recovery', description: 'Metals (steel, aluminum, copper), plastics, and non-hazardous glass recovered for recycling.' },
    ],
    siblings: [
      { slug: 'electronics/computers-laptops', name: 'Computers & Laptops' },
      { slug: 'electronics/circuit-boards', name: 'Circuit Boards' },
      { slug: 'electronics/printers-copiers', name: 'Printers & Copiers' },
    ],
    services: [{ slug: 'electronics-recycling', name: 'Electronics Recycling' }],
    faqs: [
      { q: 'Is there a fee for CRT monitor recycling?', a: 'Typically yes. CRT monitors contain 4-8 pounds of lead glass that requires specialized handling. Per-unit fees range $5-$15 depending on size and volume. LCD and LED monitors are generally free to recycle.' },
      { q: 'Can I throw old TVs in a dumpster?', a: 'In most states, no. Electronics are banned from landfill in 25+ states. CRT TVs specifically are considered hazardous waste due to lead content. Proper recycling through a certified processor is required.' },
      { q: 'What about large commercial displays?', a: 'Digital signage, video walls, and commercial displays accepted in any quantity. For large deployments, we coordinate removal and recycling as part of a refresh project.' },
    ],
    titleTag: 'Monitor & TV Recycling — LCD, LED, CRT Displays',
    metaDescription: 'Recycle monitors and TVs including CRT, LCD, and LED displays. Hazardous component handling included. Commercial and residential. 817-946-5655.',
  },
  'electronics/printers-copiers': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/printers-copiers', name: 'Printers & Copiers',
    definition: 'Printer and copier recycling recovers metals, plastics, and toner materials from inkjet, laser, and multifunction devices while properly handling toner cartridges and imaging drums.',
    acceptedItems: ['Inkjet printers', 'Laser printers', 'Multifunction printers/copiers (MFPs)', 'Large-format plotters', 'Commercial copiers and duplicators', 'Fax machines', 'Toner cartridges (all brands)', 'Ink cartridges'],
    hasDataSecurity: true,
    dataSecurity: 'Modern copiers and MFPs contain hard drives that store images of every document scanned, copied, or printed. These drives must be wiped or destroyed before recycling. We remove and destroy all storage media per NIST 800-88 with a Certificate of Destruction.',
    process: [
      { title: 'Data Destruction', description: 'Hard drives in copiers/MFPs removed and destroyed. Many users don\'t realize copiers store document images.' },
      { title: 'Toner Removal', description: 'Toner cartridges and drums removed. Cartridges refurbished where possible; toner powder properly contained.' },
      { title: 'Dismantling', description: 'Devices dismantled into metal, plastic, glass, and circuit board streams for material-specific recycling.' },
    ],
    siblings: [
      { slug: 'electronics/computers-laptops', name: 'Computers & Laptops' },
      { slug: 'electronics/monitors-tvs', name: 'Monitors & TVs' },
      { slug: 'electronics/circuit-boards', name: 'Circuit Boards' },
    ],
    services: [{ slug: 'electronics-recycling', name: 'Electronics Recycling' }, { slug: 'data-destruction', name: 'Data Destruction' }],
    faqs: [
      { q: 'Do copiers really contain hard drives?', a: 'Yes. Most modern digital copiers and MFPs manufactured after 2002 contain hard drives that store images of every document processed. This data can be recovered if the drive isn\'t properly destroyed before recycling.' },
      { q: 'Can toner cartridges be recycled separately?', a: 'Yes. We accept toner and ink cartridges. Many are refurbished for reuse. Empty cartridges can be collected in provided boxes and shipped or picked up with your next recycling haul.' },
      { q: 'Is there a cost to recycle printers?', a: 'Standard office printers and small MFPs are typically free to recycle in commercial quantities. Large commercial copiers may require assessment based on size and pickup logistics.' },
      { q: 'What about large commercial copier leases?', a: 'When your copier lease ends and the leasing company doesn\'t retrieve the device, we handle disposal. If the copier has a hard drive, data destruction is critical before the device leaves your premises.' },
    ],
    titleTag: 'Printer & Copier Recycling — Laser, Inkjet, MFPs & Toner',
    metaDescription: 'Recycle printers, copiers, and MFPs with hard drive data destruction. Toner cartridge recycling included. Free for commercial quantities. 817-946-5655.',
  },

  // ─── PALLETS ───
  'pallets/wooden-pallets': {
    parentSlug: 'pallets', parentName: 'Pallets', slug: 'pallets/wooden-pallets', name: 'Wooden Pallets',
    definition: 'Wooden pallet recycling repairs, reuses, and recycles standard and custom-size wooden pallets. Good pallets are repaired and returned to the supply chain. Damaged pallets yield reusable lumber. End-of-life pallets become mulch, animal bedding, or biomass fuel.',
    acceptedItems: ['GMA 48×40 standard pallets', 'Non-standard and custom sizes', 'Heat-treated (HT/ISPM-15) pallets', 'Euro pallets (1200×800mm)', 'Broken stringer boards and deck boards', 'Pallet collars and wooden crates'],
    hasDataSecurity: false,
    process: [
      { title: 'Grading', description: 'Tier 1: repairable. Tier 2: dismantle for lumber. Tier 3: grind for mulch or biomass.' },
      { title: 'Repair', description: 'Broken boards replaced, nails reset. Repaired pallets returned to the supply chain at a fraction of new pallet cost.' },
      { title: 'Grinding', description: 'End-of-life pallets ground into mulch, animal bedding, or biomass fuel. Nothing goes to landfill.' },
    ],
    siblings: [{ slug: 'pallets/plastic-pallets', name: 'Plastic Pallets' }],
    services: [{ slug: 'pallet-recycling', name: 'Pallet Recycling' }],
    faqs: [
      { q: 'Is wooden pallet pickup free?', a: 'For commercial volumes (20+ pallets per pickup), yes in all service cities.' },
      { q: 'Do you buy Grade A pallets?', a: 'Yes. Standard 48×40 pallets in good condition qualify for buyback or revenue share.' },
      { q: 'What about heat-treated pallets?', a: 'HT/ISPM-15 stamped pallets are accepted and recycled through the same three-tier system.' },
      { q: 'How often can you pick up?', a: 'Weekly, bi-weekly, monthly, or on-demand. High-volume sites get dedicated trailers on swap schedules.' },
    ],
    titleTag: 'Wooden Pallet Recycling — Repair, Reuse & Recycle',
    metaDescription: 'Free wooden pallet recycling pickup. Standard and custom sizes. Repair, reuse, or mulch. Buyback for Grade A pallets. 97+ cities. 817-946-5655.',
  },
  'pallets/plastic-pallets': {
    parentSlug: 'pallets', parentName: 'Pallets', slug: 'pallets/plastic-pallets', name: 'Plastic Pallets',
    definition: 'Plastic pallet recycling recovers HDPE and polypropylene from end-of-life plastic pallets, grinding them into regrind or pellets for manufacturing new plastic products.',
    acceptedItems: ['HDPE plastic pallets', 'Polypropylene (PP) pallets', 'Nestable plastic pallets', 'Rackable plastic pallets', 'Export-grade lightweight pallets', 'Broken plastic pallet pieces'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'Picked up alongside wooden pallets or in dedicated loads.' },
      { title: 'Grinding', description: 'Pallets ground into regrind/flake by resin type (HDPE or PP).' },
      { title: 'Pelletizing', description: 'Regrind processed into pellets for injection molding new plastic products.' },
    ],
    siblings: [{ slug: 'pallets/wooden-pallets', name: 'Wooden Pallets' }],
    services: [{ slug: 'pallet-recycling', name: 'Pallet Recycling' }, { slug: 'plastic-recycling', name: 'Plastic Recycling' }],
    faqs: [
      { q: 'Are plastic pallets recyclable?', a: 'Yes. HDPE and PP plastic pallets are fully recyclable into new plastic products through grinding and pelletizing.' },
      { q: 'Do you mix plastic and wooden pallet pickups?', a: 'Yes. We pick up both types in the same load and sort at our facility.' },
      { q: 'What\'s the value of plastic pallet scrap?', a: 'Clean HDPE pallet regrind has commodity value. Pricing depends on resin type, contamination level, and volume.' },
    ],
    titleTag: 'Plastic Pallet Recycling — HDPE & PP Pallets',
    metaDescription: 'Recycle HDPE and polypropylene plastic pallets. Ground into regrind for new manufacturing. Free commercial pickup. 817-946-5655.',
  },

  // ─── HAZARDOUS MATERIALS ───
  'hazardous-materials/batteries': {
    parentSlug: 'hazardous-materials', parentName: 'Hazardous Materials', slug: 'hazardous-materials/batteries', name: 'Batteries',
    definition: 'Battery recycling recovers metals and materials from all battery chemistries — lithium-ion, lead-acid, nickel-cadmium, nickel-metal hydride, and alkaline — through chemistry-specific processes at licensed facilities.',
    acceptedItems: ['Lithium-ion (laptops, phones, power tools, EVs)', 'Lead-acid (automotive, UPS, backup)', 'Nickel-cadmium (NiCd — power tools, emergency lighting)', 'Nickel-metal hydride (NiMH — hybrid vehicles, older electronics)', 'Alkaline (AA, AAA, C, D, 9V)', 'Lithium primary (button cells, medical devices)', 'Sealed lead-acid (SLA — alarm systems, scooters)'],
    hasDataSecurity: false,
    process: [
      { title: 'Sorting', description: 'Batteries sorted by chemistry — each type requires a different recycling process. Mixing chemistries is dangerous.' },
      { title: 'Packaging', description: 'DOT-compliant packaging for transport. Lithium batteries require specific packaging to prevent short circuits and fires.' },
      { title: 'Processing', description: 'Lead-acid: smelted for lead recovery. Lithium-ion: hydrometallurgical or pyrometallurgical processing for cobalt, nickel, lithium. NiCd: cadmium and nickel recovery.' },
    ],
    siblings: [
      { slug: 'hazardous-materials/light-bulbs', name: 'Light Bulbs' },
      { slug: 'hazardous-materials/chemicals', name: 'Chemicals' },
    ],
    services: [{ slug: 'hazardous-waste-disposal', name: 'Hazardous Waste Disposal' }, { slug: 'collection-events', name: 'Collection Events' }],
    faqs: [
      { q: 'Can lithium-ion batteries go in the trash?', a: 'No. Lithium batteries in landfills cause fires — they\'re responsible for hundreds of waste facility fires annually. They are classified as universal waste and must go to licensed recyclers.' },
      { q: 'How are lithium batteries packaged for transport?', a: 'DOT requires lithium batteries be packaged to prevent short circuits: terminals taped, batteries separated, in UN-rated containers. We provide compliant packaging and labeling.' },
      { q: 'What metals are recovered from batteries?', a: 'Lead from lead-acid. Cobalt, nickel, and lithium from Li-ion. Cadmium and nickel from NiCd. Steel casings from alkaline. Recovery rates exceed 95% for lead-acid and are improving rapidly for lithium-ion.' },
      { q: 'Are alkaline batteries hazardous waste?', a: 'In most states, alkaline batteries are classified as non-hazardous and can be disposed in regular trash. However, recycling is still recommended and some states (California) classify all batteries as universal waste.' },
      { q: 'Do you provide battery collection containers?', a: 'Yes. We provide DOT-compliant collection containers sized for your volume. Labels and sorting instructions included.' },
    ],
    titleTag: 'Battery Recycling — Lithium-Ion, Lead-Acid, NiCd & More',
    metaDescription: 'Recycle all battery types: lithium-ion, lead-acid, NiCd, NiMH, alkaline. DOT-compliant collection and transport. Licensed processing. 817-946-5655.',
  },
  'hazardous-materials/light-bulbs': {
    parentSlug: 'hazardous-materials', parentName: 'Hazardous Materials', slug: 'hazardous-materials/light-bulbs', name: 'Light Bulbs & Lamps',
    definition: 'Light bulb recycling safely processes mercury-containing fluorescent tubes, CFLs, HID lamps, and other lighting waste through specialized equipment that captures mercury vapor and recovers glass, aluminum, and phosphor powder.',
    acceptedItems: ['4-foot and 8-foot fluorescent tubes (T8, T12, T5)', 'Compact fluorescent lamps (CFLs)', 'High-intensity discharge (HID) lamps', 'Mercury vapor lamps', 'Metal halide lamps', 'Sodium vapor lamps', 'U-bent and circular fluorescent tubes', 'LED tubes and bulbs (non-hazardous but recyclable)'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'Lamps collected in specialized boxes that prevent breakage during transport. We provide the boxes.' },
      { title: 'Crushing/Retort', description: 'Lamps processed through specialized equipment that captures mercury vapor under negative pressure. Glass, aluminum endcaps, and phosphor powder separated.' },
      { title: 'Mercury Recovery', description: 'Captured mercury is purified and sold for reuse in new lamps and industrial applications. Recovery rate exceeds 99%.' },
    ],
    siblings: [
      { slug: 'hazardous-materials/batteries', name: 'Batteries' },
      { slug: 'hazardous-materials/chemicals', name: 'Chemicals' },
    ],
    services: [{ slug: 'hazardous-waste-disposal', name: 'Hazardous Waste Disposal' }],
    faqs: [
      { q: 'Are fluorescent bulbs hazardous waste?', a: 'Fluorescent tubes and CFLs contain mercury and are classified as universal waste under EPA rules. They cannot be disposed in regular trash and must go to licensed recyclers.' },
      { q: 'How much mercury is in a fluorescent tube?', a: 'A standard 4-foot T8 tube contains about 3-5 mg of mercury. While small per lamp, facilities with thousands of tubes accumulate significant quantities. One broken tube can contaminate a large area.' },
      { q: 'Do you provide lamp recycling boxes?', a: 'Yes. We provide specialized lamp boxes (4-foot, 8-foot, and CFL sizes) designed to prevent breakage during storage and transport. Prepaid shipping labels included for smaller quantities.' },
      { q: 'Are LED bulbs hazardous?', a: 'No. LEDs don\'t contain mercury and aren\'t classified as hazardous waste. However, they do contain recyclable metals and electronic components, so recycling is still recommended.' },
      { q: 'What\'s the cost for lamp recycling?', a: 'Per-lamp pricing depends on type and quantity. Typical range: $0.15-$0.50 per tube for commercial quantities. Volume discounts available. We provide boxes, labels, and pickup.' },
    ],
    titleTag: 'Light Bulb Recycling — Fluorescent Tubes, CFLs & HID Lamps',
    metaDescription: 'Recycle fluorescent tubes, CFLs, and HID lamps with licensed mercury recovery. Collection boxes provided. Commercial quantities. 817-946-5655.',
  },
  'hazardous-materials/chemicals': {
    parentSlug: 'hazardous-materials', parentName: 'Hazardous Materials', slug: 'hazardous-materials/chemicals', name: 'Chemicals & Solvents',
    definition: 'Chemical and solvent recycling manages the disposal of industrial chemicals, spent solvents, paint waste, lab chemicals, and cleaning agents through EPA RCRA-compliant profiling, manifesting, and licensed treatment or disposal.',
    acceptedItems: ['Spent solvents (acetone, MEK, toluene, xylene)', 'Paint and coatings waste', 'Industrial cleaning chemicals', 'Laboratory chemicals and reagents', 'Acids and bases', 'Cutting fluids and coolants', 'Adhesives and resins', 'Aerosol cans (full or partially full)'],
    hasDataSecurity: false,
    process: [
      { title: 'Profiling', description: 'Each waste stream characterized: pH, flash point, toxicity, and composition determined to establish proper EPA classification and disposal method.' },
      { title: 'Manifesting', description: 'EPA hazardous waste manifests (Form 8700-22) prepared with all required fields. LDR notifications where applicable.' },
      { title: 'Transport', description: 'DOT-compliant packaging, labeling, and transport by licensed hazmat haulers.' },
      { title: 'Treatment/Disposal', description: 'Recyclable solvents reclaimed through distillation. Non-recyclable chemicals treated (neutralization, oxidation) or incinerated at permitted facilities.' },
    ],
    siblings: [
      { slug: 'hazardous-materials/batteries', name: 'Batteries' },
      { slug: 'hazardous-materials/light-bulbs', name: 'Light Bulbs' },
    ],
    services: [{ slug: 'hazardous-waste-disposal', name: 'Hazardous Waste Disposal' }, { slug: 'waste-audits-consulting', name: 'Waste Audits' }],
    faqs: [
      { q: 'How do I know if my chemicals are hazardous waste?', a: 'If they\'re on EPA\'s listed waste tables (F, K, P, U lists) or exhibit ignitability (flash point <140°F), corrosivity (pH ≤2 or ≥12.5), reactivity, or toxicity — they\'re hazardous. We perform the profiling to determine classification.' },
      { q: 'Can spent solvents be recycled?', a: 'Many solvents can be reclaimed through distillation and reused. Acetone, MEK, toluene, and xylene are commonly reclaimed. Reclamation is often cheaper than disposal and counts as recycling for diversion metrics.' },
      { q: 'What about unknown chemicals?', a: 'We can profile unknown chemicals through laboratory analysis to determine composition and proper classification. Common in lab cleanouts and facility closures.' },
      { q: 'Do you handle lab pack services?', a: 'Yes. Lab packing involves inventorying, classifying, packaging, and manifesting multiple small containers of chemicals — common for laboratory cleanouts. We handle the full process.' },
      { q: 'What documentation do I receive?', a: 'Waste profile sheets, signed hazardous waste manifests with TSDF return copies, certificates of disposal, and LDR notifications where applicable.' },
    ],
    titleTag: 'Chemical & Solvent Recycling — EPA RCRA Compliant Disposal',
    metaDescription: 'Dispose of industrial chemicals, solvents, paint, and lab waste through EPA RCRA-compliant facilities. Full manifesting included. 817-946-5655.',
  },

  // ─── ELECTRONICS (new batch) ───
  'electronics/networking-servers': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/networking-servers', name: 'Networking & Server Equipment',
    definition: 'Networking and server equipment recycling recovers metals, circuit boards, and components from enterprise routers, switches, firewalls, server racks, UPS systems, and data center infrastructure — with certified data destruction for equipment containing network configurations and stored credentials.',
    acceptedItems: ['Network routers (Cisco, Juniper, Arista, etc.)', 'Network switches (managed and unmanaged)', 'Firewalls and security appliances', 'Wireless access points and controllers', 'Server racks and cabinets', 'Rack-mount servers (1U, 2U, 4U blade)', 'Tower servers', 'UPS / uninterruptible power supplies', 'UPS batteries (lead-acid and lithium)', 'Cable modems and DSL equipment', 'VoIP phone systems and PBX equipment', 'Patch panels and cable management', 'KVM switches and console servers', 'Load balancers', 'Network attached storage (NAS)'],
    hasDataSecurity: true,
    dataSecurity: 'Enterprise networking equipment often stores configurations, credentials, VPN keys, and SNMP community strings. Servers contain business data on hard drives and SSDs. All storage media is removed and destroyed per NIST 800-88 before material recycling. Configuration memory on routers and switches is factory-reset and verified clear. Certificate of Destruction issued per device.',
    process: [
      { title: 'Inventory', description: 'Each device logged by serial number, make, model, and asset tag. Network equipment identified by type for proper data handling.' },
      { title: 'Data Destruction', description: 'Server drives: NIST 800-88 wipe or shred. Router/switch config: factory reset + verification. UPS batteries removed for separate recycling.' },
      { title: 'Remarketing', description: 'Recent-model enterprise equipment (Cisco, Juniper, Dell, HP) tested for resale. Residual value returned to you.' },
      { title: 'Recycling', description: 'Non-reusable equipment dismantled: circuit boards to precious metal refiners, steel chassis to scrap, copper wiring recovered, plastics sorted by resin.' },
    ],
    siblings: [
      { slug: 'electronics/computers-laptops', name: 'Computers & Laptops' },
      { slug: 'electronics/circuit-boards', name: 'Circuit Boards' },
      { slug: 'electronics/storage-drives', name: 'Storage & Drives' },
      { slug: 'electronics/wires-cables', name: 'Wires & Cables' },
    ],
    services: [{ slug: 'it-asset-disposition', name: 'IT Asset Disposition' }, { slug: 'electronics-recycling', name: 'Electronics Recycling' }, { slug: 'data-destruction', name: 'Data Destruction' }],
    faqs: [
      { q: 'Do servers need data destruction before recycling?', a: 'Yes. Server hard drives and SSDs contain business data that must be destroyed per NIST 800-88 before any material recycling. We remove and destroy all storage media and provide per-drive Certificates of Destruction.' },
      { q: 'What about network router configurations?', a: 'Enterprise routers store configurations, credentials, VPN keys, and routing tables. We factory-reset all networking equipment and verify the configuration memory is clear before processing.' },
      { q: 'Can we get value for old Cisco equipment?', a: 'Yes. Recent-model Cisco, Juniper, Arista, and other enterprise networking equipment often has significant resale value. We test, refurbish, and resell through our channels — net recovery returned to you.' },
      { q: 'How do you handle UPS batteries?', a: 'UPS batteries (typically sealed lead-acid or lithium-ion) are removed and recycled separately through licensed battery processors. Lead-acid batteries are nearly 100% recyclable. DOT-compliant packaging and transport included.' },
      { q: 'Do you handle full data center decommissions?', a: 'Yes. We coordinate complete data center decommissions: servers, networking, storage, UPS, cabling, and racks. Serial-number tracking, data destruction, and asset recovery across the entire facility.' },
    ],
    titleTag: 'Networking & Server Recycling — Routers, Switches, Racks & UPS',
    metaDescription: 'Recycle networking equipment and servers with data destruction. Cisco, Juniper, server racks, UPS. R2 certified. Enterprise asset recovery. 817-946-5655.',
  },
  'electronics/storage-drives': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/storage-drives', name: 'Storage & Drives',
    definition: 'Storage drive recycling handles the secure destruction and material recovery of hard disk drives (HDDs), solid state drives (SSDs), tape drives, optical drives, and external storage devices — with NIST 800-88 compliant data destruction as the mandatory first step.',
    acceptedItems: ['Hard disk drives (HDD) — 3.5" desktop, 2.5" laptop', 'Solid state drives (SSD) — SATA, NVMe, M.2', 'Enterprise SAS drives', 'Tape drives and tape cartridges (LTO, DLT)', 'Floppy drives and diskettes', 'CD/DVD/Blu-ray drives (optical)', 'External hard drives and SSDs', 'USB flash drives and thumb drives', 'Memory cards (SD, microSD, CompactFlash)', 'RAID arrays and controllers'],
    hasDataSecurity: true,
    dataSecurity: 'Storage drives are the highest-risk component in any electronics recycling stream. Every drive — HDD, SSD, tape, flash — contains potentially recoverable data until properly destroyed. We offer three NIST 800-88 destruction levels: Clear (software overwrite for drive reuse), Purge (degaussing for HDDs or cryptographic erase for SEDs), and Destroy (physical shredding). Certificate of Destruction per drive with serial number, method, and date.',
    process: [
      { title: 'Intake & Logging', description: 'Every drive logged by serial number, capacity, and type. Chain-of-custody documented from your facility to ours.' },
      { title: 'Destruction Method', description: 'Based on your security requirements: software overwrite (NIST Clear), degaussing (NIST Purge — HDDs only), or physical shredding (NIST Destroy — all drive types).' },
      { title: 'Verification', description: 'Software-wiped drives verified via read-back. Degaussed drives tested with field meter. Shredded drives reduced to particles below data recovery threshold.' },
      { title: 'Material Recovery', description: 'Destroyed drives yield aluminum platters, rare earth magnets (neodymium), circuit boards with precious metals, and steel housings.' },
    ],
    siblings: [
      { slug: 'electronics/computers-laptops', name: 'Computers & Laptops' },
      { slug: 'electronics/networking-servers', name: 'Networking & Servers' },
      { slug: 'electronics/circuit-boards', name: 'Circuit Boards' },
    ],
    services: [{ slug: 'data-destruction', name: 'Data Destruction' }, { slug: 'it-asset-disposition', name: 'IT Asset Disposition' }, { slug: 'shredding-services', name: 'Media Shredding' }],
    faqs: [
      { q: 'Can data be recovered from a formatted drive?', a: 'Yes. Standard formatting only removes the file system index — data remains on the platters and is recoverable with forensic tools. Even a "full format" doesn\'t overwrite all sectors. NIST 800-88 compliant destruction is required for actual data elimination.' },
      { q: 'Does degaussing work on SSDs?', a: 'No. Degaussing only works on magnetic media (HDDs and tapes). SSDs use flash memory chips that are not affected by magnetic fields. SSDs require cryptographic erasure (for self-encrypting drives) or physical shredding.' },
      { q: 'What\'s the difference between Clear, Purge, and Destroy?', a: 'Clear: logical overwrite — data unrecoverable by standard tools, drive reusable. Purge: degaussing or cryptographic erase — data unrecoverable by laboratory techniques, drive may not be reusable. Destroy: physical shredding — media reduced to particles, no recovery possible under any circumstances.' },
      { q: 'Do you offer onsite drive shredding?', a: 'Yes. Our mobile shredding trucks come to your location. Drives are destroyed on premises while you watch. Certificates of Destruction issued before our truck departs. Ideal for highest-security environments.' },
      { q: 'What materials are recovered from hard drives?', a: 'HDDs contain: aluminum platters, rare earth neodymium magnets (valuable), circuit boards with gold/silver, steel housings, and copper windings. SSDs contain circuit boards with precious metals and NAND flash chips with trace metals.' },
    ],
    titleTag: 'Storage & Drive Recycling — HDD, SSD, Tape & Flash Destruction',
    metaDescription: 'Secure destruction and recycling of hard drives, SSDs, tape drives, and flash storage. NIST 800-88 certified. Per-drive COD. Onsite available. 817-946-5655.',
  },
  'electronics/peripherals': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/peripherals', name: 'Peripherals & Accessories',
    definition: 'Peripheral recycling handles keyboards, mice, speakers, headsets, webcams, adapters, chargers, power supplies, docking stations, and other computer accessories — recovering metals, plastics, and small amounts of circuit board material.',
    acceptedItems: ['Keyboards (wired and wireless)', 'Mice and trackpads', 'Computer speakers and soundbars', 'Headsets and headphones', 'Webcams', 'Adapters and chargers (laptop, phone, universal)', 'Power supplies (ATX, laptop bricks)', 'Docking stations and port replicators', 'USB hubs', 'Card readers', 'Drawing tablets (Wacom, etc.)', 'External DVD/Blu-ray drives', 'Surge protectors and power strips', 'Ink and toner cartridges', 'Gaming controllers and accessories'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'Peripherals collected in gaylord boxes or bins. Often combined with computer recycling pickups at no additional charge.' },
      { title: 'Sorting', description: 'Separated by type: electronics with circuit boards (keyboards, mice) vs pure plastic/metal (adapters, cables) vs batteries (wireless devices).' },
      { title: 'Processing', description: 'Circuit boards extracted for precious metal recovery. Plastics sorted by resin. Metals (steel, aluminum, copper) separated. Batteries removed for licensed recycling.' },
    ],
    siblings: [
      { slug: 'electronics/computers-laptops', name: 'Computers & Laptops' },
      { slug: 'electronics/wires-cables', name: 'Wires & Cables' },
      { slug: 'electronics/printers-copiers', name: 'Printers & Copiers' },
      { slug: 'electronics/audio-video', name: 'Audio/Video Equipment' },
    ],
    services: [{ slug: 'electronics-recycling', name: 'Electronics Recycling' }, { slug: 'business-recycling-programs', name: 'Business Recycling Programs' }],
    faqs: [
      { q: 'Is there a cost to recycle peripherals?', a: 'Typically free when combined with computer or electronics recycling pickups. Standalone peripheral-only pickups may require minimum volumes. Contact us for specific terms.' },
      { q: 'Do wireless peripherals contain batteries?', a: 'Yes. Wireless keyboards, mice, and headsets contain rechargeable lithium batteries that must be removed and recycled separately. We handle the battery separation.' },
      { q: 'Can ink and toner cartridges be recycled with peripherals?', a: 'Yes. Ink and toner cartridges are accepted. Many are refurbished for reuse; spent cartridges are recycled for plastic and metal recovery.' },
      { q: 'What about large quantities from an office refresh?', a: 'We handle any volume. Office-wide peripheral cleanouts during IT refreshes are common — keyboards, mice, headsets, and chargers across hundreds of workstations. We provide bins and coordinate pickup.' },
    ],
    titleTag: 'Peripheral & Accessory Recycling — Keyboards, Mice, Chargers & More',
    metaDescription: 'Recycle computer peripherals: keyboards, mice, speakers, chargers, adapters, headsets. Free with electronics pickup. Commercial quantities. 817-946-5655.',
  },
  'electronics/audio-video': {
    parentSlug: 'electronics', parentName: 'Electronics', slug: 'electronics/audio-video', name: 'Audio/Video Equipment',
    definition: 'Audio/video equipment recycling handles VCRs, DVD/Blu-ray players, stereo receivers, amplifiers, projectors, cable/satellite boxes, gaming consoles, and other entertainment electronics — recovering circuit boards, metals, and plastics from end-of-life devices.',
    acceptedItems: ['VCRs and VHS players', 'DVD and Blu-ray players', 'CD players and changers', 'Stereo receivers and amplifiers', 'Home theater systems', 'Projectors (LCD, DLP, LED)', 'Cable boxes and satellite receivers', 'TV cable boxes and set-top boxes', 'Gaming consoles (PlayStation, Xbox, Nintendo)', 'Streaming devices (Roku, Apple TV, Fire Stick)', 'Record players and turntables', 'Cassette players and boomboxes', 'Digital cameras and camcorders', 'Professional audio/video equipment', 'Karaoke machines', 'Typewriters (electric)'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'Picked up with general electronics. No special packaging needed for most A/V equipment.' },
      { title: 'Testing', description: 'Recent-model devices (gaming consoles, streaming devices, projectors) tested for refurbishment potential and resale value.' },
      { title: 'Dismantling', description: 'Non-reusable devices dismantled: circuit boards extracted for precious metals, transformers removed for copper, steel/aluminum chassis separated, plastics sorted by resin.' },
    ],
    siblings: [
      { slug: 'electronics/monitors-tvs', name: 'Monitors & TVs' },
      { slug: 'electronics/peripherals', name: 'Peripherals & Accessories' },
      { slug: 'electronics/computers-laptops', name: 'Computers & Laptops' },
    ],
    services: [{ slug: 'electronics-recycling', name: 'Electronics Recycling' }, { slug: 'junk-removal', name: 'Junk Removal' }],
    faqs: [
      { q: 'Can gaming consoles be recycled?', a: 'Yes. PlayStation, Xbox, and Nintendo consoles are accepted. Recent-model working consoles may have resale value. Non-working consoles are dismantled for circuit board and metal recovery. Make sure to remove any game discs and wipe your account before recycling.' },
      { q: 'What about old VCRs and tape players?', a: 'Yes. VCRs, cassette players, and other legacy A/V equipment are accepted. They contain small amounts of copper, aluminum, and circuit board material worth recovering.' },
      { q: 'Do cable boxes need to be returned to the cable company?', a: 'Usually yes — cable and satellite boxes are typically leased equipment. Check with your provider first. If you own the box (purchased outright or the provider says to keep it), we\'ll recycle it.' },
      { q: 'Is there a cost for A/V equipment recycling?', a: 'Standard A/V equipment is typically free to recycle in commercial quantities. Projectors with mercury-containing lamps may have a small per-unit handling fee. Contact us for specific terms.' },
      { q: 'Do you handle commercial A/V equipment from businesses?', a: 'Yes. Conference room projectors, professional audio systems, digital signage components, and event A/V equipment. We coordinate pickup and provide documentation for asset disposition.' },
    ],
    titleTag: 'Audio/Video Equipment Recycling — VCRs, Projectors, Consoles & More',
    metaDescription: 'Recycle audio/video equipment: VCRs, DVD players, projectors, gaming consoles, cable boxes, stereos. Free for commercial quantities. 817-946-5655.',
  },

  // ─── PLASTICS ───
  'plastics/hdpe': {
    parentSlug: 'plastics', parentName: 'Plastics', slug: 'plastics/hdpe', name: 'HDPE (#2)',
    definition: 'HDPE (High-Density Polyethylene, resin code #2) is the most widely recycled rigid plastic. It\'s used for milk jugs, detergent bottles, pipes, buckets, pallets, totes, and industrial drums. HDPE is valued by reprocessors for its strength, chemical resistance, and consistent melt properties.',
    acceptedItems: ['Water pipes and fittings', 'Hula hoop rings', 'Five gallon buckets', 'Milk, juice, and water bottles', 'Grocery bags (in baled quantities)', 'Shampoo and toiletry bottles', 'Plastic pallets (HDPE)', 'Totes and storage bins', 'Pipe and conduit', 'Buckets and pails', 'Cups and containers', 'Bottles and jugs', 'Dunnage trays', 'Film (HDPE bags, baled)', 'Obsolete parts and production scrap'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'HDPE collected by type: natural (clear/white — highest value), colored, and mixed. Containers separated from film.' },
      { title: 'Baling', description: 'Sorted HDPE baled to spec for transport to reprocessors. Clean, single-color bales command premium pricing.' },
      { title: 'Washing & Grinding', description: 'At the reprocessor: labels removed, material washed, ground into flake, floated to remove contaminants.' },
      { title: 'Pelletizing', description: 'Clean flake melted and extruded into pellets for injection molding, blow molding, or pipe extrusion.' },
    ],
    siblings: [{ slug: 'plastics/pet', name: 'PET (#1)' }, { slug: 'plastics/pp', name: 'PP (#5)' }, { slug: 'plastics/ldpe-film', name: 'LDPE / Film' }, { slug: 'plastics/pvc', name: 'PVC (#3)' }, { slug: 'plastics/engineering-plastics', name: 'Engineering Plastics' }, { slug: 'plastics/polystyrene', name: 'Polystyrene (#6)' }],
    services: [{ slug: 'plastic-recycling', name: 'Plastic Recycling' }, { slug: 'business-recycling-programs', name: 'Business Programs' }],
    faqs: [
      { q: 'What\'s HDPE worth?', a: 'Clean natural (clear/white) HDPE commands the best price — typically $0.10-$0.30/lb depending on form and market. Colored HDPE pays less. Mixed or contaminated HDPE may have little or no value. We quote based on your specific material.' },
      { q: 'Can HDPE pipes be recycled?', a: 'Yes. HDPE pipe from plumbing, irrigation, and conduit is accepted. Long lengths may need to be cut for baling. Clean pipe without soil contamination gets the best rates.' },
      { q: 'What about 5-gallon buckets?', a: 'Yes — HDPE buckets are a common commercial stream. Clean buckets (no hazardous residue) are recycled as rigid HDPE. Buckets that contained food products need rinsing. Buckets with chemical residue may need special handling.' },
      { q: 'Is there a minimum for HDPE pickup?', a: 'For free pickup, we typically need 500+ lbs of clean, sorted HDPE. Ongoing generators with regular volumes get scheduled collection with containers provided.' },
    ],
    titleTag: 'HDPE Recycling (#2) — Bottles, Buckets, Pipes, Pallets & Drums',
    metaDescription: 'Recycle HDPE plastic: bottles, buckets, pipes, pallets, drums. Natural and colored HDPE accepted. Commercial quantities. 817-946-5655.',
  },
  'plastics/pet': {
    parentSlug: 'plastics', parentName: 'Plastics', slug: 'plastics/pet', name: 'PET (#1)',
    definition: 'PET (Polyethylene Terephthalate, resin code #1) is the clear plastic used for beverage bottles, food containers, and thermoform packaging. It\'s one of the most valuable recyclable plastics due to strong demand from bottle-to-bottle recycling programs and polyester fiber manufacturing.',
    acceptedItems: ['Soft drink and water bottles', 'Salad dressing bottles', 'Peanut butter jars', 'Jam and preserve jars', 'Thermoform clamshells and trays', 'PET strapping and banding', 'Clear food containers', 'Pharmaceutical bottles'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'PET collected separately from other resins. Clear PET has the highest value; green and colored PET pay less.' },
      { title: 'Baling', description: 'Sorted, compacted, and baled for transport. Labels and caps removed at the reprocessor.' },
      { title: 'Washing', description: 'Hot-washed to remove labels, adhesives, and contaminants. Floated to separate PET from other plastics.' },
      { title: 'Pelletizing', description: 'Clean PET flake pelletized for bottle-to-bottle recycling or extruded into polyester fiber for textiles and insulation.' },
    ],
    siblings: [{ slug: 'plastics/hdpe', name: 'HDPE (#2)' }, { slug: 'plastics/pp', name: 'PP (#5)' }, { slug: 'plastics/ldpe-film', name: 'LDPE / Film' }],
    services: [{ slug: 'plastic-recycling', name: 'Plastic Recycling' }, { slug: 'business-recycling-programs', name: 'Business Programs' }],
    faqs: [
      { q: 'Is clear PET worth more than colored?', a: 'Yes. Clear PET commands the highest price because it can be recycled into new clear bottles (bottle-to-bottle). Green and blue PET is worth less. Mixed-color PET is worth the least.' },
      { q: 'Can PET thermoforms (clamshells) be recycled?', a: 'Yes, though not all facilities accept them. PET thermoforms have a different melt profile than bottle-grade PET. We route thermoforms to processors equipped to handle them.' },
      { q: 'What\'s the difference between PET and PETE?', a: 'They\'re the same material. PET (Polyethylene Terephthalate) is the industry term. PETE is the consumer-facing abbreviation used in the resin identification coding system.' },
    ],
    titleTag: 'PET Recycling (#1) — Bottles, Containers & Thermoforms',
    metaDescription: 'Recycle PET plastic: beverage bottles, food containers, thermoform packaging. Clear and colored PET accepted. Commercial quantities. 817-946-5655.',
  },
  'plastics/pp': {
    parentSlug: 'plastics', parentName: 'Plastics', slug: 'plastics/pp', name: 'PP (#5)',
    definition: 'PP (Polypropylene, resin code #5) is a versatile plastic used for yogurt containers, bottle caps, automotive parts, industrial totes, supersacks, and plastic pallets. PP has a higher melting point than PE, making it suitable for hot-fill applications and microwave-safe containers.',
    acceptedItems: ['Reusable microwaveable containers', 'Kitchenware and food storage', 'Yogurt containers and margarine tubs', 'Microwaveable takeaway containers', 'Disposable cups and plates', 'Plastic pallets (PP)', 'Totes and supersacks', 'Cups and pipe fittings', 'Obsolete parts and production scrap'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'PP collected and sorted by color and form. Post-industrial scrap (clean, single-resin) commands premium pricing.' },
      { title: 'Grinding', description: 'Bulky items (pallets, totes) ground into regrind. Small items baled.' },
      { title: 'Washing', description: 'Post-consumer PP washed to remove food residue and labels. Post-industrial typically needs minimal cleaning.' },
      { title: 'Pelletizing', description: 'Clean PP regrind compounded into pellets for injection molding and extrusion. Often blended with virgin for consistent properties.' },
    ],
    siblings: [{ slug: 'plastics/hdpe', name: 'HDPE (#2)' }, { slug: 'plastics/pet', name: 'PET (#1)' }, { slug: 'plastics/ldpe-film', name: 'LDPE / Film' }],
    services: [{ slug: 'plastic-recycling', name: 'Plastic Recycling' }, { slug: 'pallet-recycling', name: 'Pallet Recycling' }],
    faqs: [
      { q: 'Are yogurt containers recyclable?', a: 'Yes. PP yogurt tubs, margarine containers, and food-grade PP are recyclable. They must be rinsed. Recycling infrastructure for PP has expanded significantly in recent years.' },
      { q: 'What about PP supersacks?', a: 'PP woven supersacks (bulk bags / FIBCs) are a high-value recycling stream. Clean supersacks are recycled into PP pellets. We accept commercial quantities from manufacturing and logistics operations.' },
    ],
    titleTag: 'PP Recycling (#5) — Containers, Pallets, Totes & Supersacks',
    metaDescription: 'Recycle polypropylene plastic: containers, pallets, totes, supersacks, kitchenware. Commercial and industrial PP. 817-946-5655.',
  },
  'plastics/ldpe-film': {
    parentSlug: 'plastics', parentName: 'Plastics', slug: 'plastics/ldpe-film', name: 'LDPE / Film (#4)',
    definition: 'LDPE (Low-Density Polyethylene, resin code #4) film recycling recovers stretch wrap, shrink film, bags, and flexible packaging from commercial operations. Film is one of the largest commercial plastic waste streams by volume — a single distribution center can generate thousands of pounds of stretch wrap per month.',
    acceptedItems: ['Stretch wrap (pallet wrap)', 'Obsolete roll stock', 'Baled clear and printed film', 'Frozen food bags', 'Squeezable bottles', 'Cling films and flexible packaging', 'Flexible container lids', 'Grocery and retail bags (baled)', 'Poly mailers and shipping bags', 'Greenhouse film'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'Film collected in dedicated containers or baled on-site. Keeping film clean and dry is critical — wet or contaminated film loses value.' },
      { title: 'Baling', description: 'Film baled to density specs for transport. On-site balers provided for high-volume generators.' },
      { title: 'Washing', description: 'Film washed in hot water to remove labels, ink, and contaminants. Multiple wash stages for post-consumer film.' },
      { title: 'Pelletizing', description: 'Clean film extruded into LDPE pellets for blown film manufacturing — new bags, film, and flexible packaging.' },
    ],
    siblings: [{ slug: 'plastics/hdpe', name: 'HDPE (#2)' }, { slug: 'plastics/pet', name: 'PET (#1)' }, { slug: 'plastics/pp', name: 'PP (#5)' }],
    services: [{ slug: 'plastic-recycling', name: 'Plastic Recycling' }, { slug: 'business-recycling-programs', name: 'Business Programs' }, { slug: 'cardboard-paper-recycling', name: 'Cardboard & Paper' }],
    faqs: [
      { q: 'How much stretch wrap does a DC need to generate for pickup?', a: 'For free collection, we typically need 500+ lbs per pickup (about one gaylord box). DCs wrapping 200+ pallets/day usually generate this in 1-2 weeks. We provide collection containers and schedule based on your volume.' },
      { q: 'Does printed film have value?', a: 'Yes, though less than clear film. Printed LDPE film is recycled into dark-colored products (trash bags, construction film). Clear film commands 2-3x the price of printed.' },
      { q: 'Can we bale our own film?', a: 'Yes — and it increases value significantly. Baled film is denser, cheaper to transport, and commands premium pricing. We can provide or help source a vertical or horizontal baler for high-volume operations.' },
      { q: 'What about contaminated stretch wrap?', a: 'Film contaminated with food, moisture, or adhesive labels is harder to recycle and may not have value. The cleaner and drier the film, the better the rate. We assess contamination levels during the audit.' },
    ],
    titleTag: 'LDPE Film Recycling (#4) — Stretch Wrap, Shrink Film & Bags',
    metaDescription: 'Recycle LDPE film: stretch wrap, shrink film, bags, poly mailers. Commercial volumes from DCs and manufacturing. Free pickup. 817-946-5655.',
  },
  'plastics/pvc': {
    parentSlug: 'plastics', parentName: 'Plastics', slug: 'plastics/pvc', name: 'PVC (#3)',
    definition: 'PVC (Polyvinyl Chloride, resin code #3) recycling recovers rigid pipe, cable insulation, window profiles, vinyl siding, and blister packaging. PVC is widely used in construction and infrastructure but requires specialized recycling due to chlorine content.',
    acceptedItems: ['Blister packaging (non-food)', 'Cling films for non-food use', 'Electrical cable insulation', 'Rigid PVC piping', 'Vinyl records', 'Window profile regrind', 'PVC parts and trim', 'PVC pipe fittings and valves', 'PVC clamshells', 'Vinyl siding and gutters'],
    hasDataSecurity: false,
    process: [
      { title: 'Sorting', description: 'PVC must be separated from other plastics — PVC contamination ruins PET and HDPE recycling batches. NIR sorting or manual separation.' },
      { title: 'Grinding', description: 'Rigid PVC (pipe, profiles, siding) ground into regrind. Flexible PVC (cable, film) processed separately.' },
      { title: 'Compounding', description: 'PVC regrind blended with stabilizers and processed into pellets for new pipe, profiles, and construction products.' },
    ],
    siblings: [{ slug: 'plastics/hdpe', name: 'HDPE (#2)' }, { slug: 'plastics/pet', name: 'PET (#1)' }, { slug: 'plastics/pp', name: 'PP (#5)' }],
    services: [{ slug: 'plastic-recycling', name: 'Plastic Recycling' }],
    faqs: [
      { q: 'Can PVC pipe be recycled?', a: 'Yes. Clean PVC pipe from plumbing, irrigation, and construction is recyclable. It\'s ground into regrind and re-extruded into new pipe. Soil-contaminated pipe needs washing before processing.' },
      { q: 'Why is PVC kept separate from other plastics?', a: 'PVC contains chlorine, which causes processing problems when mixed with PET or HDPE. Even a small amount of PVC contamination can ruin an entire batch of other plastics. Proper sorting is critical.' },
      { q: 'What about vinyl siding?', a: 'Yes. Vinyl siding tear-off from renovation and demolition is recyclable PVC. Clean siding (no paint, no nails) gets the best rates.' },
    ],
    titleTag: 'PVC Recycling (#3) — Pipe, Cable, Window Profiles & Siding',
    metaDescription: 'Recycle PVC plastic: rigid pipe, cable insulation, window profiles, vinyl siding. Specialized PVC processing. Commercial quantities. 817-946-5655.',
  },
  'plastics/engineering-plastics': {
    parentSlug: 'plastics', parentName: 'Plastics', slug: 'plastics/engineering-plastics', name: 'Engineering Plastics',
    definition: 'Engineering plastics recycling recovers high-performance resins — ABS, Nylon, PBT, Polycarbonate (PC), and PC/ABS blends — from manufacturing scrap, production rejects, and end-of-life products. These materials have significantly higher value per pound than commodity plastics.',
    acceptedItems: ['ABS — Regrind, parts, virgin resin, sheets, all forms and colors', 'HDPE industrial — Pallets, totes, pipe, dunnage trays, obsolete parts', 'Nylon — 66, 6, 6/12, 11, glass-filled, mineral-filled, unfilled, regrind and parts', 'PBT — Regrind, parts, virgin resin in all forms and colors', 'PC (Polycarbonate) — Regrind, parts, virgin resin, sheets, Plexiglas, Lucite, scrap, bottles', 'PC/ABS — Beverage bottles, baby bottles, compact discs, electronic housings, automotive headlamps, instrument panels', 'Acetal (POM) — Gears, bushings, fasteners, production scrap'],
    hasDataSecurity: false,
    process: [
      { title: 'Identification', description: 'Resin identified by FTIR (Fourier Transform Infrared) analysis or burn testing. Accurate identification is critical — engineering plastics command 5-10x commodity prices.' },
      { title: 'Sorting', description: 'Separated by resin type, color, and grade. Filled vs unfilled. Virgin vs regrind. Cross-contamination between resin types eliminated.' },
      { title: 'Grinding', description: 'Parts and runners ground to consistent particle size. Screened to remove fines and oversized pieces.' },
      { title: 'Compounding', description: 'Regrind blended, pelletized, and quality-tested to meet specification for injection molding. Often sold back into the same industry that generated the scrap.' },
    ],
    siblings: [{ slug: 'plastics/hdpe', name: 'HDPE (#2)' }, { slug: 'plastics/pet', name: 'PET (#1)' }, { slug: 'plastics/pp', name: 'PP (#5)' }],
    services: [{ slug: 'plastic-recycling', name: 'Plastic Recycling' }, { slug: 'business-recycling-programs', name: 'Business Programs' }],
    faqs: [
      { q: 'How much are engineering plastics worth?', a: 'Significantly more than commodity plastics. Clean ABS regrind can be $0.30-$0.60/lb. Nylon and PC are often higher. Virgin resin overstock or off-spec material commands the best prices. We quote based on resin type, grade, and volume.' },
      { q: 'Do you accept production runners and sprues?', a: 'Yes — injection molding runners, sprues, and purge material are our most common engineering plastic stream. Keep resins separated (don\'t mix ABS with PC) for best value.' },
      { q: 'What about glass-filled nylon?', a: 'Yes. Glass-filled nylon (GF-Nylon 66, GF-Nylon 6) is accepted. Glass content must be identified — 30% glass-filled nylon is processed differently than unfilled. We test glass content before pricing.' },
      { q: 'Can you handle large quantities from a plant closure?', a: 'Yes. Plant closures and production line changes often generate large volumes of engineering plastic scrap — inventory, WIP, regrind stockpiles, and reject parts. We coordinate rapid pickup and processing.' },
    ],
    titleTag: 'Engineering Plastics Recycling — ABS, Nylon, PC, PBT & Blends',
    metaDescription: 'Recycle engineering plastics: ABS, Nylon, Polycarbonate, PBT, PC/ABS. Production scrap and regrind. Premium pricing. 817-946-5655.',
  },
  'plastics/polystyrene': {
    parentSlug: 'plastics', parentName: 'Plastics', slug: 'plastics/polystyrene', name: 'Polystyrene (#6)',
    definition: 'Polystyrene (PS, resin code #6) recycling handles both expanded polystyrene (EPS — foam) and high-impact polystyrene (HIPS — rigid). EPS packaging, packing peanuts, foam insulation, and rigid PS containers like disposable cups and food trays are all recyclable in commercial quantities.',
    acceptedItems: ['Egg cartons (foam)', 'Packing peanuts (loose fill)', 'Disposable cups (foam and rigid)', 'Plates, trays, and cutlery', 'Disposable take-away containers', 'EPS packaging blocks and inserts', 'Foam insulation board', 'HIPS (High-Impact Polystyrene) production scrap'],
    hasDataSecurity: false,
    process: [
      { title: 'Collection', description: 'EPS is extremely bulky relative to weight. Densifying on-site (compacting or melting into blocks) dramatically reduces transport cost.' },
      { title: 'Densifying', description: 'Foam compressed at 50:1 ratio or melted into ingots. This is the critical step — shipping un-densified foam is economically impractical.' },
      { title: 'Pelletizing', description: 'Densified PS reprocessed into pellets for injection molding — picture frames, crown molding, coat hangers, and new packaging.' },
    ],
    siblings: [{ slug: 'plastics/hdpe', name: 'HDPE (#2)' }, { slug: 'plastics/pet', name: 'PET (#1)' }, { slug: 'plastics/pp', name: 'PP (#5)' }],
    services: [{ slug: 'plastic-recycling', name: 'Plastic Recycling' }],
    faqs: [
      { q: 'Is styrofoam actually recyclable?', a: 'Yes — EPS (expanded polystyrene, commonly called "styrofoam") is technically recyclable. The challenge is economics: it\'s 98% air, making it extremely expensive to transport. Densifying (compressing) on-site makes EPS recycling viable for commercial quantities.' },
      { q: 'Do you provide foam densifiers?', a: 'For high-volume generators (shipping/receiving operations, cold chain logistics), we can coordinate foam densifier equipment. Densified EPS is 50x denser than loose foam and has real commodity value.' },
      { q: 'What about packing peanuts?', a: 'Loose fill packing peanuts are accepted in commercial quantities. They\'re reused where possible or densified and pelletized. Some facilities accept clean peanuts for direct reuse by shipping companies.' },
      { q: 'Are foam food containers recyclable?', a: 'Clean foam food containers are technically recyclable, but food-contaminated foam is not. Many municipalities ban PS food containers entirely. For commercial operations, clean PS packaging (not food service) is the viable recycling stream.' },
    ],
    titleTag: 'Polystyrene Recycling (#6) — EPS Foam, Cups, Trays & Packaging',
    metaDescription: 'Recycle polystyrene: EPS foam packaging, packing peanuts, disposable cups, trays. Densifying available. Commercial quantities. 817-946-5655.',
  },

  // ─── HAZARDOUS MATERIALS (additional) ───
  'hazardous-materials/medical-waste': {
    parentSlug: 'hazardous-materials', parentName: 'Hazardous Materials', slug: 'hazardous-materials/medical-waste', name: 'Medical Waste',
    definition: 'Medical waste (regulated medical waste / biohazardous waste) includes sharps, pathological waste, blood-contaminated materials, and infectious waste generated by healthcare facilities. Medical waste is regulated separately from standard hazardous waste under OSHA Bloodborne Pathogens Standard, state health department rules, and DOT transport regulations.',
    acceptedItems: ['Sharps (needles, syringes, lancets, scalpels)', 'Blood-soaked bandages and dressings', 'Pathological waste (tissues, organs)', 'Microbiological waste (cultures, specimens)', 'Contaminated PPE (gowns, gloves, masks)', 'IV tubing and bags with blood residue', 'Pharmaceutical waste (non-controlled)', 'Chemotherapy waste (trace and bulk)', 'Animal waste from veterinary facilities'],
    hasDataSecurity: false,
    process: [
      { title: 'Segregation', description: 'Medical waste must be segregated at the point of generation: sharps in puncture-resistant containers, biohazard waste in red bags, pathological waste separately. Proper segregation is the single biggest cost factor.' },
      { title: 'Collection', description: 'Licensed medical waste haulers collect on schedule using DOT-compliant vehicles. Containers tracked with manifests or shipping papers.' },
      { title: 'Treatment', description: 'Autoclaving (steam sterilization), incineration, or chemical treatment depending on waste type and state regulations. Treated waste is then safe for standard landfill disposal.' },
      { title: 'Documentation', description: 'Tracking documents, treatment certificates, and manifest copies provided. Documentation meets OSHA, state health department, and Joint Commission requirements.' },
    ],
    siblings: [
      { slug: 'hazardous-materials/batteries', name: 'Batteries' },
      { slug: 'hazardous-materials/light-bulbs', name: 'Light Bulbs' },
      { slug: 'hazardous-materials/chemicals', name: 'Chemicals & Solvents' },
    ],
    services: [{ slug: 'hazardous-waste-disposal', name: 'Hazardous Waste Disposal' }, { slug: 'business-recycling-programs', name: 'Business Programs' }],
    faqs: [
      { q: 'What qualifies as regulated medical waste?', a: 'Items contaminated with blood or other potentially infectious materials (OPIM): sharps, blood-soaked bandages, pathological waste, microbiological cultures, and certain contaminated PPE. The definition varies by state — some states regulate more broadly than OSHA\'s federal standard.' },
      { q: 'What\'s the biggest cost driver for medical waste?', a: 'Over-segregation — putting general waste in red bags. Studies consistently show 20-40% of red bag waste isn\'t actually regulated medical waste. Proper training and segregation protocols dramatically reduce costs by shifting volume from expensive RMW treatment to standard disposal.' },
      { q: 'How is medical waste treated?', a: 'Three primary methods: autoclaving (steam sterilization at 250°F/15 PSI — most common), incineration (for pathological and chemotherapy waste), and chemical treatment (for specific waste types). The method depends on waste type and your state\'s regulations.' },
      { q: 'Do you handle pharmaceutical waste?', a: 'Non-controlled pharmaceutical waste (expired, recalled, contaminated medications) is managed under EPA\'s pharmaceutical waste rule. Controlled substances (Schedule II-V) require DEA reverse distribution. We handle both streams.' },
      { q: 'What about sharps from non-healthcare businesses?', a: 'Any business generating sharps (needles, lancets) needs a sharps management program — even non-healthcare settings like tattoo parlors, veterinary clinics, and manufacturing facilities that use syringes. We provide sharps containers and scheduled pickup.' },
    ],
    titleTag: 'Medical Waste Disposal — Sharps, Biohazard & Regulated Waste',
    metaDescription: 'Medical waste disposal: sharps, biohazard, pathological, pharmaceutical. Licensed collection, autoclaving, and documentation. Healthcare compliant. 817-946-5655.',
  },
};
