// ─── MATERIAL PAGE DATA ───

export type MaterialPageData = {
  slug: string;
  name: string;
  icon: string;
  heroImage: string;
  definition: string;
  overview: string[];
  // Sub-types (only for parent materials with children)
  subTypes?: { slug: string; name: string; description: string }[];
  acceptedItems: string[];
  process: { title: string; description: string }[];
  // Why Recycle section — environmental impact
  whyRecycle: { stat: string; description: string }[];
  // Cross-links
  services: { slug: string; name: string; context: string }[];
  challenges: { slug: string; title: string; pain: string }[];
  industries: { slug: string; name: string; context: string }[];
  // City links for local SEO
  cityLinks: { slug: string; name: string; urlPrefix: string }[];
  faqs: { q: string; a: string }[];
  certifications: string[];
  titleTag: string;
  metaDescription: string;
  h1: string;
  headlines: {
    overview: string;
    subTypes?: string;
    acceptedItems: string;
    process: string;
    whyRecycle: string;
    services: string;
    challenges: string;
    industries: string;
    cityLinks: string;
    faq: string;
    faqSubtitle: string;
    cta: string;
    ctaSubtitle: string;
  };
};

export const MATERIAL_PAGES: Record<string, MaterialPageData> = {
  'metals': {
    slug: 'metals',
    name: 'Scrap Metal',
    icon: 'iron',
    heroImage: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=1600&h=600&fit=crop',
    definition: 'Scrap metal recycling recovers ferrous metals (iron, steel, cast iron) and non-ferrous metals (copper, aluminum, brass, stainless steel) from end-of-life products, industrial scrap, and construction debris. Metals are infinitely recyclable — they can be melted and reformed without any loss in quality.',
    headlines: {
      overview: 'Every Metal Has Value. None Belongs in a Landfill.',
      subTypes: 'Metal Types We Process',
      acceptedItems: 'What Qualifies as Scrap Metal',
      process: 'How Metal Gets From Your Facility to the Mill',
      whyRecycle: 'The Environmental Case for Metal Recycling',
      services: 'Services for Metal Recycling',
      challenges: 'Problems Metal Recycling Solves',
      industries: 'Who Generates the Most Scrap Metal',
      cityLinks: 'Recycle Scrap Metal in Your City',
      faq: 'Metal Recycling Questions',
      faqSubtitle: 'Pricing, grades, and what makes metal worth recycling.',
      cta: 'Get a Scrap Metal Quote',
      ctaSubtitle: 'Tell us what metals you have and we\'ll quote a price. Free pickup for commercial volumes.',
    },
    overview: [
      'The United States recycles more than 80 million tons of iron and steel annually — more than paper, plastic, aluminum, and glass combined. Scrap metal is one of the most valuable recyclable materials in the commercial waste stream, and unlike paper or plastic, metals can be recycled infinitely without degradation in quality.',
      'Every ton of recycled steel saves 2,500 pounds of iron ore, 1,400 pounds of coal, and 120 pounds of limestone. For non-ferrous metals like copper and aluminum, the energy savings are even more dramatic — recycling aluminum uses 95% less energy than producing it from raw bauxite ore.',
    ],
    subTypes: [
      { slug: 'ferrous-metals', name: 'Ferrous Metals', description: 'Iron, steel, cast iron, wrought iron — magnetic metals used in construction, manufacturing, and automotive' },
      { slug: 'non-ferrous-metals/copper', name: 'Copper', description: 'Wire, pipe, sheet, and plumbing fixtures — one of the highest-value recyclable metals' },
      { slug: 'non-ferrous-metals/aluminum', name: 'Aluminum', description: 'Extrusions, cans, sheet, and castings — recycling uses 95% less energy than virgin production' },
      { slug: 'non-ferrous-metals/brass', name: 'Brass', description: 'Fittings, valves, fixtures, and decorative hardware — copper-zinc alloy with strong resale value' },
      { slug: 'stainless-steel', name: 'Stainless Steel', description: '304, 316, and other grades — food equipment, medical devices, architectural elements' },
    ],
    acceptedItems: [
      'Steel beams, plates, and structural steel',
      'Cast iron pipes, grates, and fixtures',
      'Copper wire, pipe, and sheet',
      'Aluminum extrusions, cans, and sheet',
      'Brass fittings, valves, and fixtures',
      'Stainless steel (all grades)',
      'Auto parts: engines, transmissions, body panels',
      'Industrial equipment and machinery',
      'Racking, shelving, and warehouse fixtures',
      'HVAC ductwork, units, and copper coils',
      'Catalytic converters',
      'Mixed and unsorted scrap metal',
    ],
    process: [
      { title: 'Assessment', description: 'We evaluate your scrap — types, estimated weight, and condition. Photos help us quote faster.' },
      { title: 'Pricing', description: 'Quotes based on daily commodity rates, metal type, and volume. Non-ferrous metals command the highest prices.' },
      { title: 'Pickup', description: 'We bring the container and haul it. Roll-offs, flatbeds, or grapple trucks depending on volume and type.' },
      { title: 'Processing', description: 'Scrap is weighed on certified scales, sorted by grade, and processed for resale to domestic mills and foundries.' },
      { title: 'Payment & Certificate', description: 'You receive payment at the quoted rate plus a Certificate of Recycling for compliance records.' },
    ],
    whyRecycle: [
      { stat: '80M+ tons', description: 'of iron and steel recycled annually in the US — more than all other recyclable materials combined' },
      { stat: '95% less energy', description: 'to recycle aluminum compared to mining and processing raw bauxite ore' },
      { stat: '2,500 lbs', description: 'of iron ore saved per ton of recycled steel, plus 1,400 lbs of coal and 120 lbs of limestone' },
      { stat: '∞ recyclable', description: 'Metals can be melted and reformed indefinitely with zero quality degradation' },
    ],
    services: [
      { slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling', context: 'Our core metal recycling service — competitive pricing, free commercial pickup, and certified processing.' },
      { slug: 'dumpster-rental', name: 'Dumpster Rental', context: 'Roll-off containers for large-volume metal scrap from demolition, manufacturing, or equipment decommission.' },
      { slug: 'business-recycling-programs', name: 'Business Recycling Programs', context: 'Ongoing metal recycling as part of a comprehensive multi-stream program for your facility.' },
    ],
    challenges: [
      { slug: 'cost-reduction', title: 'Scrap Metal Sitting in Your Yard Is Lost Revenue', pain: 'Unlike most recyclables, metals have real commodity value. If they\'re going in the dumpster, you\'re paying to throw away money.' },
      { slug: 'waste-diversion', title: 'The Fastest Way to Boost Your Diversion Rate', pain: 'Adding a metal recycling stream can improve your diversion rate by 20-30 points overnight. It\'s 100% recyclable.' },
    ],
    industries: [
      { slug: 'manufacturing', name: 'Manufacturing', context: 'CNC turnings, stamping scrap, offcuts, and end-of-line equipment generate consistent metal volumes from production operations.' },
      { slug: 'construction', name: 'Construction', context: 'Rebar, structural steel, HVAC, plumbing, and demo scrap. Job sites and demolition projects are major metal sources.' },
      { slug: 'automotive', name: 'Automotive', context: 'Body panels, engines, transmissions, catalytic converters, and end-of-life vehicles — every auto part has recoverable metal.' },
      { slug: 'logistics', name: 'Distribution & Logistics', context: 'Warehouse racking, shelving, conveyor systems, and equipment decommissions produce steel and aluminum scrap.' },
    ],
    cityLinks: [
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'scrap-metal-recycling' },
      { slug: 'houston', name: 'Houston', urlPrefix: 'scrap-metal-recycling' },
      { slug: 'dallas-fort-worth', name: 'Dallas / Fort Worth', urlPrefix: 'scrap-metal-recycling' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'scrap-metal-recycling' },
      { slug: 'atlanta', name: 'Atlanta', urlPrefix: 'scrap-metal-recycling' },
      { slug: 'detroit', name: 'Detroit', urlPrefix: 'scrap-metal-recycling' },
      { slug: 'philadelphia', name: 'Philadelphia', urlPrefix: 'scrap-metal-recycling' },
      { slug: 'new-york-city', name: 'New York City', urlPrefix: 'scrap-metal-recycling' },
      { slug: 'miami-fort-lauderdale', name: 'Miami', urlPrefix: 'scrap-metal-recycling' },
      { slug: 'toronto-mississauga', name: 'Toronto', urlPrefix: 'scrap-metal-recycling' },
    ],
    faqs: [
      { q: 'What types of scrap metal are worth the most?', a: 'Non-ferrous metals command the highest prices: copper wire and pipe, brass fittings, and aluminum extrusions typically pay the most per pound. Clean, sorted non-ferrous scrap is worth significantly more than mixed or contaminated loads. Ferrous metals (steel, iron) pay less per pound but are accepted in much larger volumes.' },
      { q: 'How do I know if my metal is ferrous or non-ferrous?', a: 'The simplest test: if a magnet sticks to it, it\'s ferrous (iron-based). If not, it\'s non-ferrous. Common ferrous metals include steel, cast iron, and wrought iron. Common non-ferrous metals include copper, aluminum, brass, stainless steel, and lead.' },
      { q: 'Do you pick up scrap metal for free?', a: 'For commercial volumes (generally 1+ ton of ferrous or 200+ lbs of non-ferrous), we provide free pickup. For smaller quantities, you can drop off at a partner yard. High-value non-ferrous metals may qualify for free pickup at lower quantities.' },
      { q: 'How is scrap metal priced?', a: 'Pricing follows daily commodity markets (LME, COMEX). We quote based on metal type, grade (clean vs contaminated), and volume. Prices fluctuate daily — we honor quoted prices for 48 hours. You can verify our rates against any published commodity index.' },
      { q: 'Can I recycle mixed or unsorted scrap?', a: 'Yes. We accept mixed loads and sort at our facility. However, pre-sorted scrap by type earns higher rates because it reduces processing costs. If you can separate ferrous from non-ferrous, you\'ll get a better price.' },
      { q: 'What documentation do I get?', a: 'Weight tickets for every load (certified scales), payment records, and a Certificate of Recycling. For ESG reporting, we provide annual summaries with tonnage, carbon offset calculations, and processing details.' },
      { q: 'Do you buy catalytic converters?', a: 'Yes. Catalytic converters contain platinum, palladium, and rhodium — precious metals with significant value. We require valid ID and vehicle documentation to comply with state theft-prevention laws. Pricing depends on the converter type and precious metal content.' },
      { q: 'What happens to recycled metal?', a: 'Scrap is sold to domestic mills and foundries where it\'s melted, purified, and formed into new steel, aluminum, copper, or brass products. Recycled metal re-enters manufacturing supply chains for automotive, construction, electronics, and consumer goods. Nothing is exported to developing countries.' },
    ],
    certifications: ['ISRI member', 'ISO 14001', 'State-licensed', 'Certified scales'],
    titleTag: 'Scrap Metal Recycling — Copper, Aluminum, Steel & Brass',
    metaDescription: 'Recycle scrap metal with competitive pricing for copper, aluminum, steel, brass, and stainless steel. Free commercial pickup in 97+ cities. 817-946-5655.',
    h1: 'Scrap Metal Recycling — Copper, Aluminum, Steel & Brass',
  },

  'electronics': {
    slug: 'electronics',
    name: 'Electronics',
    icon: 'devices',
    heroImage: 'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=1600&h=600&fit=crop',
    definition: 'Electronics recycling (e-waste recycling) recovers valuable materials — gold, silver, copper, palladium, and rare earth elements — from end-of-life electronic devices while ensuring data security and compliance with EPA regulations. E-waste is the fastest-growing waste stream globally, with only 25% properly recycled in the US.',
    headlines: {
      overview: 'The World\'s Fastest-Growing Waste Stream, Handled Right',
      subTypes: 'Types of E-Waste We Recycle',
      acceptedItems: 'Devices and Equipment We Accept',
      process: 'From Your Dock to Certified Recycling',
      whyRecycle: 'Why E-Waste Can\'t Go in the Trash',
      services: 'E-Waste Services',
      challenges: 'The Risks of Improper E-Waste Disposal',
      industries: 'Who Generates the Most E-Waste',
      cityLinks: 'E-Waste Recycling in Your City',
      faq: 'Electronics Recycling Questions',
      faqSubtitle: 'Data security, what\'s accepted, and what happens to your old equipment.',
      cta: 'Get a Free E-Waste Quote',
      ctaSubtitle: 'Send us your equipment list and we\'ll handle everything — data destruction, pickup, and certified recycling.',
    },
    overview: [
      'Electronic waste contains a paradox: it\'s simultaneously one of the most valuable and most hazardous materials in the waste stream. A single ton of circuit boards contains more gold than a ton of gold ore. But those same circuit boards also contain lead, mercury, cadmium, and brominated flame retardants that contaminate soil and groundwater when landfilled.',
      'For businesses, the risk goes beyond environmental damage. Hard drives, SSDs, and mobile devices contain sensitive data that doesn\'t disappear when you throw the device away. A single improperly disposed hard drive can trigger a data breach costing millions. Proper e-waste recycling includes certified data destruction before any material recovery begins.',
    ],
    subTypes: [
      { slug: 'cell-phones', name: 'Cell Phones & Mobile Devices', description: 'Smartphones, tablets, iPads, feature phones, smartwatches — all brands, any condition' },
      { slug: 'computers-laptops', name: 'Computers & Laptops', description: 'Desktops, laptops, Chromebooks, workstations, Mac and PC — with certified data destruction' },
      { slug: 'circuit-boards', name: 'Circuit Boards', description: 'Motherboards, PCBs, and components — precious metal recovery from gold, silver, palladium' },
      { slug: 'wires-cables', name: 'Wires & Cables', description: 'Network cables, power cords, copper wiring — copper and insulation recovery' },
      { slug: 'monitors-tvs', name: 'Monitors & TVs', description: 'LCD, LED, CRT displays — including hazardous CRT glass handling' },
      { slug: 'printers-copiers', name: 'Printers & Copiers', description: 'Inkjet, laser, multifunction — including toner cartridge recycling' },
    ],
    acceptedItems: [
      'Desktop computers, towers, and workstations',
      'Laptops, Chromebooks, and notebooks',
      'Monitors (LCD, LED, CRT)',
      'Cell phones, smartphones, and tablets',
      'Printers, copiers, scanners, and fax machines',
      'Servers and rack-mount equipment',
      'Networking gear: routers, switches, firewalls, access points',
      'UPS systems and backup batteries',
      'Hard drives, SSDs, and tape media',
      'Cables, keyboards, mice, and peripherals',
      'AV equipment and teleconference systems',
      'Point-of-sale (POS) terminals and kiosks',
    ],
    process: [
      { title: 'Inventory', description: 'We catalog equipment by type and quantity. For ITAD, every device is tracked by serial number.' },
      { title: 'Data Destruction', description: 'All data-bearing devices wiped or shredded per NIST 800-88. Certificate of Destruction per drive.' },
      { title: 'Pickup', description: 'Secure, GPS-tracked transport from your facility to our processing center. Full chain-of-custody.' },
      { title: 'Disassembly', description: 'Equipment dismantled into material streams: circuit boards, metals, plastics, glass, and hazardous components.' },
      { title: 'Certificate', description: 'Certificate of Recycling with weight, material breakdown, and diversion rate. Asset disposition report for ITAD.' },
    ],
    whyRecycle: [
      { stat: '62M tonnes', description: 'of e-waste generated globally in 2022 — only 22% was properly collected and recycled (WHO/UN)' },
      { stat: '$62B in value', description: 'worth of recoverable raw materials in global e-waste each year, mostly lost to landfill' },
      { stat: '70% of toxic waste', description: 'in US landfills comes from electronic equipment (EPA estimate)' },
      { stat: '$4.88M average', description: 'cost of a data breach in 2024 — improperly disposed devices are a top risk vector (IBM)' },
    ],
    services: [
      { slug: 'electronics-recycling', name: 'Electronics Recycling', context: 'Full-service e-waste recycling with R2/e-Stewards certification and data destruction.' },
      { slug: 'it-asset-disposition', name: 'IT Asset Disposition', context: 'Secure ITAD with serial-number tracking, remarketing, and compliance documentation.' },
      { slug: 'data-destruction', name: 'Data Destruction', context: 'NIST 800-88 certified wiping, degaussing, and physical shredding with per-drive COD.' },
    ],
    challenges: [
      { slug: 'ewaste-compliance', title: 'EPA Fines and Data Breach Liability', pain: 'Improper e-waste disposal exposes you to both environmental fines and data security lawsuits. R2 certification and Certificates of Destruction are your legal protection.' },
      { slug: 'hazardous-waste', title: 'CRTs, Batteries, and Mercury', pain: 'Many electronic components contain hazardous materials that require licensed handling — not just standard recycling.' },
    ],
    industries: [
      { slug: 'banking-finance', name: 'Banking & Finance', context: 'ATMs, workstations, servers, and networking equipment with GLBA data destruction requirements.' },
      { slug: 'healthcare', name: 'Healthcare', context: 'Patient monitoring systems, imaging equipment, and workstations containing HIPAA-regulated data.' },
      { slug: 'education', name: 'Education & Government', context: 'Chromebook fleets, desktop labs, and campus networking equipment on 3-5 year refresh cycles.' },
      { slug: 'retail', name: 'Retail', context: 'POS systems, back-office computers, digital signage, and networking equipment across store locations.' },
    ],
    cityLinks: [
      { slug: 'new-york-city', name: 'New York City', urlPrefix: 'electronics-recycling' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'electronics-recycling' },
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'electronics-recycling' },
      { slug: 'san-francisco-oakland', name: 'San Francisco', urlPrefix: 'electronics-recycling' },
      { slug: 'seattle-tacoma', name: 'Seattle', urlPrefix: 'electronics-recycling' },
      { slug: 'austin', name: 'Austin', urlPrefix: 'electronics-recycling' },
      { slug: 'boston', name: 'Boston', urlPrefix: 'electronics-recycling' },
      { slug: 'toronto-mississauga', name: 'Toronto', urlPrefix: 'electronics-recycling' },
      { slug: 'greater-london', name: 'London', urlPrefix: 'electronics-recycling' },
      { slug: 'sydney', name: 'Sydney', urlPrefix: 'electronics-recycling' },
    ],
    faqs: [
      { q: 'What electronics do you accept for recycling?', a: 'We accept virtually all electronic equipment: computers, laptops, monitors (including CRTs), cell phones, tablets, printers, servers, networking equipment, UPS systems, cables, peripherals, POS terminals, and AV equipment. If it has a circuit board or a plug, we can probably recycle it.' },
      { q: 'Is data destroyed before recycling?', a: 'Yes. All data-bearing devices (hard drives, SSDs, phones, tablets, tape media) undergo NIST 800-88 compliant data destruction before any material recovery. You receive a Certificate of Destruction documenting the method, date, and serial number of each device.' },
      { q: 'What certifications should I look for?', a: 'R2 (Responsible Recycling) and e-Stewards are the gold standard. They certify that downstream processors follow documented procedures for data security, environmental management, and material handling. Our network holds both certifications plus ISO 14001.' },
      { q: 'Can you handle CRT monitors and TVs?', a: 'Yes. CRTs contain 4-8 pounds of lead each and require specialized handling. We process them through licensed facilities that recover the lead and glass. CRTs typically carry a per-unit processing fee due to the hazardous material content.' },
      { q: 'Is there a cost for e-waste recycling?', a: 'Standard IT equipment (computers, laptops, servers, phones) is typically free to recycle. Items with negative commodity value (CRT monitors, some printers, non-working UPS batteries) may have a per-unit fee. We provide a detailed quote upfront.' },
      { q: 'What happens to the materials recovered?', a: 'Circuit boards go to precious metal refiners (gold, silver, palladium recovery). Copper is extracted from wiring. Aluminum and steel housings go to metal recyclers. Plastics are sorted by resin type for reprocessing. Nothing is exported to developing countries.' },
      { q: 'Can you track individual assets?', a: 'Yes. Our ITAD service tracks every device by serial number from your facility through data destruction and final disposition. The asset disposition report provides a complete audit trail for your IT asset management and compliance records.' },
      { q: 'How quickly can you schedule pickup?', a: 'Most pickups are scheduled within 3-5 business days. Expedited and same-week service available in major metros for office moves, lease expirations, and urgent decommissions.' },
    ],
    certifications: ['R2', 'e-Stewards', 'NIST 800-88', 'ISO 14001'],
    titleTag: 'Electronics Recycling — E-Waste Disposal & Data Destruction',
    metaDescription: 'Recycle electronics with certified data destruction. Computers, cell phones, monitors, servers, and more. Free pickup in 97+ cities. 817-946-5655.',
    h1: 'Electronics Recycling — Certified E-Waste Disposal',
  },

  'paper-cardboard': {
    slug: 'paper-cardboard',
    name: 'Paper & Cardboard',
    icon: 'description',
    heroImage: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=1600&h=600&fit=crop',
    definition: 'Paper and cardboard recycling collects and reprocesses corrugated cardboard (OCC), office paper, newspaper, magazines, and mixed paper into new fiber products. Paper is the most recycled material by weight in the United States, with a recovery rate above 65%.',
    headlines: {
      overview: 'The Most Recycled Material in America',
      acceptedItems: 'Paper Grades We Accept',
      process: 'From Collection to New Fiber',
      whyRecycle: 'Why Paper Recycling Matters',
      services: 'Services for Paper & Cardboard',
      challenges: 'The Cardboard Problem at Scale',
      industries: 'Top Paper & Cardboard Generators',
      cityLinks: 'Paper Recycling in Your City',
      faq: 'Paper & Cardboard Questions',
      faqSubtitle: 'Contamination, grades, and when cardboard becomes revenue.',
      cta: 'Get a Cardboard Recycling Quote',
      ctaSubtitle: 'Tell us your volume and we\'ll set up a program that keeps your dock clear and your recycling documented.',
    },
    overview: [
      'Paper and cardboard represent the largest single component of the commercial waste stream for most businesses — especially retail, distribution, and office environments. The good news: paper fiber is highly recyclable and has established commodity markets. The challenge is volume management, contamination control, and getting pickup frequency right.',
      'Recycling Quotes provides scheduled paper and cardboard recycling with the right container for your volume — from desk-side bins and toters to compactors and balers for high-volume generators. Clean OCC at sufficient volume often qualifies for commodity rebates, turning a disposal cost into revenue.',
    ],
    acceptedItems: ['Old corrugated containers (OCC)', 'Office paper (white and colored)', 'Mixed paper and junk mail', 'Newspaper and inserts', 'Magazines and catalogs', 'Kraft paper and bags', 'Paperboard and cereal boxes', 'Phone books and directories', 'Shredded paper (must be bagged)', 'Books (hardcover and softcover)'],
    process: [
      { title: 'Assessment', description: 'We evaluate your paper and cardboard volume, where it accumulates, and current disposal costs.' },
      { title: 'Equipment', description: 'Right-sized container: toters, dumpsters, compactors, or balers depending on your generation rate.' },
      { title: 'Pickup', description: 'Scheduled service matched to your volume. Frequency adjusts seasonally.' },
      { title: 'Processing', description: 'Paper sorted by grade, baled, and shipped to domestic mills for reprocessing into new products.' },
      { title: 'Documentation', description: 'Weight tickets and Certificate of Recycling with tonnage diverted for your records.' },
    ],
    whyRecycle: [
      { stat: '#1 recycled', description: 'Paper is the most recycled material by weight in the US — over 65% recovery rate' },
      { stat: '17 trees', description: 'saved per ton of recycled paper, plus 7,000 gallons of water and 4,100 kWh of energy' },
      { stat: '25%', description: 'of landfill waste is paper and cardboard — the single largest component' },
      { stat: '5-7 cycles', description: 'Paper fiber can be recycled 5-7 times before it becomes too short for new paper' },
    ],
    services: [
      { slug: 'cardboard-paper-recycling', name: 'Cardboard & Paper Recycling', context: 'Dedicated paper and OCC recycling with compactors, balers, and scheduled pickup.' },
      { slug: 'shredding-services', name: 'Shredding Services', context: 'Secure destruction of confidential documents with certified recycling of shredded fiber.' },
      { slug: 'business-recycling-programs', name: 'Business Recycling Programs', context: 'Paper recycling as part of a comprehensive multi-stream program for your facility.' },
    ],
    challenges: [
      { slug: 'cost-reduction', title: 'Clean Cardboard Is Worth Money', pain: 'At high volumes, OCC generates commodity rebates. If your cardboard is going to landfill, you\'re paying disposal fees on something that has market value.' },
      { slug: 'waste-diversion', title: 'The Easiest Diversion Win', pain: 'Paper and cardboard make up 25% of landfill waste. Separating them from your general waste stream is the fastest way to improve your diversion rate.' },
    ],
    industries: [
      { slug: 'retail', name: 'Retail', context: 'Every shipment arrives in cardboard. Stores receive dozens of boxes daily — making retail the single largest source of commercial OCC.' },
      { slug: 'logistics', name: 'Distribution & Logistics', context: 'DCs process massive volumes of cardboard and packaging. On-site balers and compactors are essential for high-throughput operations.' },
      { slug: 'manufacturing', name: 'Manufacturing', context: 'Inbound packaging, production waste paper, and outbound shipping materials create multi-grade paper waste streams.' },
    ],
    cityLinks: [
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'cardboard-paper-recycling' },
      { slug: 'dallas-fort-worth', name: 'Dallas / Fort Worth', urlPrefix: 'cardboard-paper-recycling' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'cardboard-paper-recycling' },
      { slug: 'new-york-city', name: 'New York City', urlPrefix: 'cardboard-paper-recycling' },
      { slug: 'houston', name: 'Houston', urlPrefix: 'cardboard-paper-recycling' },
      { slug: 'atlanta', name: 'Atlanta', urlPrefix: 'cardboard-paper-recycling' },
      { slug: 'philadelphia', name: 'Philadelphia', urlPrefix: 'cardboard-paper-recycling' },
      { slug: 'phoenix', name: 'Phoenix', urlPrefix: 'cardboard-paper-recycling' },
      { slug: 'seattle-tacoma', name: 'Seattle', urlPrefix: 'cardboard-paper-recycling' },
      { slug: 'toronto-mississauga', name: 'Toronto', urlPrefix: 'cardboard-paper-recycling' },
    ],
    faqs: [
      { q: 'What types of paper can be recycled?', a: 'We accept OCC (corrugated cardboard), office paper, mixed paper, newspaper, magazines, kraft paper, paperboard, shredded paper (bagged), and books. The key: materials must be dry and free of food contamination.' },
      { q: 'Can greasy pizza boxes be recycled?', a: 'No. Grease-soaked cardboard contaminates the recycling batch. Clean portions of pizza boxes can be torn off and recycled; greasy portions go to compost or trash.' },
      { q: 'Do you pay for cardboard?', a: 'Clean OCC at sufficient volume (typically 2+ tons per pickup) often qualifies for commodity rebates. Market prices fluctuate — we pass through current rates and adjust quarterly.' },
      { q: 'What\'s the difference between OCC and mixed paper?', a: 'OCC is corrugated cardboard (the kind with the wavy flute layer). It\'s a higher-grade commodity. Mixed paper includes everything else: office paper, junk mail, magazines, paperboard. OCC pays more and has more stable markets.' },
      { q: 'Do you provide compactors or balers?', a: 'Yes. For businesses generating 2+ tons per week, compactors or balers reduce volume by 50-90%, cutting pickup frequency and costs. Equipment provided at no additional charge for qualifying volumes.' },
      { q: 'Can shredded paper be recycled?', a: 'Yes, but it must be bagged to prevent it from blowing during transport. Shredded paper has lower commodity value than whole paper because the fibers are shortened, but it\'s still recyclable.' },
      { q: 'How do I reduce contamination?', a: 'Keep paper and cardboard dry and separate from food waste. We provide sorting signage and employee training to minimize contamination. The most common contaminants: food-soiled paper, waxed cardboard, and plastic bags mixed with paper.' },
      { q: 'What documentation do I receive?', a: 'Weight tickets per pickup, monthly tonnage summaries, and a Certificate of Recycling. Annual sustainability data available for ESG reporting.' },
    ],
    certifications: ['SFI certified mills', 'ISO 14001', 'State-licensed'],
    titleTag: 'Paper & Cardboard Recycling — OCC, Office Paper & More',
    metaDescription: 'Recycle cardboard, office paper, and mixed paper with scheduled pickup and compactor/baler options. Revenue share available. 97+ cities. 817-946-5655.',
    h1: 'Paper & Cardboard Recycling — OCC, Office Paper & More',
  },

  'plastics': {
    slug: 'plastics',
    name: 'Plastics',
    icon: 'water_bottle',
    heroImage: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=1600&h=600&fit=crop',
    definition: 'Plastic recycling recovers and reprocesses HDPE, PET, PP, and LDPE plastics from commercial waste streams into reusable raw materials. Only about 5-6% of plastic waste in the US is currently recycled — but commercial operations generating clean, sorted streams can achieve dramatically higher rates.',
    headlines: {
      overview: 'Making Plastic Recycling Actually Work',
      acceptedItems: 'Plastic Types We Process',
      process: 'From Waste Stream to Pellet',
      whyRecycle: 'The Plastic Problem by the Numbers',
      services: 'Plastic Recycling Services',
      challenges: 'Why Most Plastic Doesn\'t Get Recycled',
      industries: 'Top Plastic Waste Generators',
      cityLinks: 'Plastic Recycling in Your City',
      faq: 'Plastic Recycling Questions',
      faqSubtitle: 'Which resins, contamination rules, and what actually gets recycled.',
      cta: 'Get a Plastic Recycling Quote',
      ctaSubtitle: 'Tell us your plastic types and volumes. We\'ll design a collection program that maximizes recovery.',
    },
    overview: [
      'The national plastic recycling rate of 5-6% is misleading for commercial operations. The problem isn\'t that plastic can\'t be recycled — it\'s that most programs collect mixed, contaminated streams that are too expensive to sort. Clean, source-separated commercial plastic consistently achieves recovery rates of 80-95%.',
      'Recycling Quotes designs plastic recycling programs around your specific resin types and generation patterns. Whether it\'s HDPE containers from a production line, stretch wrap from a distribution center, or PET bottles from a cafeteria, we set up collection that keeps streams clean and marketable.',
    ],
    acceptedItems: ['PET bottles and containers (#1)', 'HDPE containers, jugs, and drums (#2)', 'PP containers, caps, and packaging (#5)', 'LDPE/LLDPE stretch wrap and film (#4)', 'Rigid plastic packaging', 'Industrial plastic scrap and cutoffs', 'Plastic pallets and crates', 'Plastic drums and IBCs', 'Polycarbonate and acrylic'],
    process: [
      { title: 'Identify', description: 'We assess your resin types, volumes, and contamination levels. Clean, single-resin streams get the best rates.' },
      { title: 'Collect', description: 'Containers, bags, or roll-offs — sized and placed where plastic accumulates in your operation.' },
      { title: 'Sort', description: 'Pickups go to our facility for sorting by resin type. Mixed loads are separated; contaminated material is removed.' },
      { title: 'Process', description: 'Clean plastic is baled and shipped to domestic reprocessors where it\'s washed, pelletized, and sold back into manufacturing.' },
    ],
    whyRecycle: [
      { stat: '5-6%', description: 'of US plastic waste is actually recycled — commercial programs can do 10-20x better with clean streams' },
      { stat: '400+ years', description: 'for plastic to decompose in a landfill — it doesn\'t biodegrade, it just breaks into smaller pieces' },
      { stat: '8M tons', description: 'of plastic enters the ocean every year globally — recycling keeps it in the economy, not the environment' },
      { stat: '80% less energy', description: 'to make products from recycled plastic compared to virgin resin production' },
    ],
    services: [
      { slug: 'plastic-recycling', name: 'Plastic Recycling', context: 'Dedicated commercial plastic recycling with collection, sorting, and domestic processing.' },
      { slug: 'business-recycling-programs', name: 'Business Recycling Programs', context: 'Plastic as part of a comprehensive multi-stream program with consolidated reporting.' },
      { slug: 'dumpster-rental', name: 'Dumpster Rental', context: 'Roll-off containers for large-volume plastic waste from production or renovation.' },
    ],
    challenges: [
      { slug: 'waste-diversion', title: 'Plastic Drags Your Diversion Rate Down', pain: 'If plastic goes to landfill, it sits there for centuries. Even modest plastic recycling improves your overall diversion rate by 5-10 points.' },
      { slug: 'esg-reporting', title: 'Stakeholders Are Watching Plastic', pain: 'Plastic waste is the most visible environmental issue. Documented plastic recycling is a powerful signal in sustainability reports.' },
    ],
    industries: [
      { slug: 'manufacturing', name: 'Manufacturing', context: 'Production scrap, runners, sprues, and rejected parts from injection molding and extrusion are often recyclable at near-commodity value.' },
      { slug: 'retail', name: 'Retail', context: 'Shrink wrap, product packaging, and display materials create consistent recyclable plastic volumes across store networks.' },
      { slug: 'logistics', name: 'Distribution & Logistics', context: 'Stretch wrap from pallet wrapping is one of the most recyclable commercial plastic streams — thousands of pounds per month from a single DC.' },
    ],
    cityLinks: [
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'plastic-recycling' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'plastic-recycling' },
      { slug: 'dallas-fort-worth', name: 'Dallas / Fort Worth', urlPrefix: 'plastic-recycling' },
      { slug: 'houston', name: 'Houston', urlPrefix: 'plastic-recycling' },
      { slug: 'atlanta', name: 'Atlanta', urlPrefix: 'plastic-recycling' },
      { slug: 'new-york-city', name: 'New York City', urlPrefix: 'plastic-recycling' },
      { slug: 'phoenix', name: 'Phoenix', urlPrefix: 'plastic-recycling' },
      { slug: 'detroit', name: 'Detroit', urlPrefix: 'plastic-recycling' },
      { slug: 'seattle-tacoma', name: 'Seattle', urlPrefix: 'plastic-recycling' },
      { slug: 'toronto-mississauga', name: 'Toronto', urlPrefix: 'plastic-recycling' },
    ],
    faqs: [
      { q: 'Which plastic types do you recycle?', a: 'PET (#1), HDPE (#2), PP (#5), and LDPE/LLDPE (#4 film and stretch wrap). These are the most commonly recyclable commercial plastics. PVC (#3), PS (#6), and mixed (#7) have limited recyclability.' },
      { q: 'What about stretch wrap?', a: 'Stretch wrap (LDPE/LLDPE) is highly recyclable when collected clean and separate. We provide dedicated film collection for DCs and warehouses generating high volumes.' },
      { q: 'Does contamination matter?', a: 'Yes — food residue, mixed resins, and non-plastic attachments reduce recyclability. Clean, sorted, single-resin streams have the highest recovery rates.' },
      { q: 'Is recycled plastic actually recycled domestically?', a: 'We use domestic reprocessors only. Plastic is baled and shipped to US facilities for washing, pelletizing, and resale into manufacturing.' },
      { q: 'Can mixed plastics be recycled?', a: 'Yes, but recovery rates are lower. We sort mixed loads by resin type at our facility. Source-separating your highest-volume resin types improves economics.' },
      { q: 'Is there revenue from plastic recycling?', a: 'Clean, baled HDPE, PET, and stretch wrap film have commodity value at sufficient volumes (1+ ton/month). Rebates fluctuate with market prices.' },
      { q: 'What\'s the minimum volume?', a: 'For dedicated plastic pickup: 500+ lbs/month of a single resin or 1,000+ lbs mixed. Smaller volumes can join a comprehensive recycling program.' },
      { q: 'What about plastic that can\'t be recycled?', a: 'Non-recyclable plastics go to waste-to-energy facilities where available, recovering energy content rather than landfilling.' },
    ],
    certifications: ['ISO 14001', 'APR certified processors', 'EPA compliant'],
    titleTag: 'Plastic Recycling — HDPE, PET, PP & Stretch Wrap',
    metaDescription: 'Commercial plastic recycling for HDPE, PET, PP, and stretch wrap. Domestic processing, no export. 97+ cities. 817-946-5655.',
    h1: 'Plastic Recycling — HDPE, PET, PP & Stretch Wrap',
  },

  'pallets': {
    slug: 'pallets',
    name: 'Pallets',
    icon: 'pallet',
    heroImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1600&h=600&fit=crop',
    definition: 'Pallet recycling recovers wooden and plastic pallets from commercial operations through repair, reuse, and material recovery. Over 2 billion pallets circulate in the US supply chain annually — pallets in good condition are repaired and returned to service, while end-of-life pallets are processed into mulch, biomass, or recycled lumber.',
    headlines: {
      overview: 'Two Billion Pallets. Zero Should Go to Landfill.',
      subTypes: 'Pallet Types We Handle',
      acceptedItems: 'What We Pick Up',
      process: 'Repair, Reuse, or Recycle',
      whyRecycle: 'The Pallet Economy',
      services: 'Pallet Services',
      challenges: 'The Cost of Pallet Waste',
      industries: 'Who Generates the Most Pallets',
      cityLinks: 'Pallet Recycling in Your City',
      faq: 'Pallet Recycling Questions',
      faqSubtitle: 'Free pickup, buyback, and what happens to your pallets.',
      cta: 'Get a Free Pallet Recycling Quote',
      ctaSubtitle: 'Tell us your volume and we\'ll have a quote within 24 hours. Free pickup for commercial quantities.',
    },
    overview: [
      'Pallets are one of the most recyclable items in the commercial waste stream — yet millions end up in landfills every year. The economics are simple: good pallets are worth repairing, damaged pallets yield reusable lumber, and end-of-life pallets produce mulch and biomass fuel. Nothing needs to go to waste.',
      'For high-volume generators like distribution centers and manufacturers, pallet recycling isn\'t just environmentally responsible — it\'s free. We pick up at no charge for qualifying commercial volumes, and for Grade A pallets, we offer buyback programs that turn your waste into revenue.',
    ],
    subTypes: [
      { slug: 'wooden-pallets', name: 'Wooden Pallets', description: 'Standard GMA 48×40, custom sizes, heat-treated (ISPM-15), and all grades' },
      { slug: 'plastic-pallets', name: 'Plastic Pallets', description: 'HDPE and PP pallets — recycled into new plastic products or pellets' },
    ],
    acceptedItems: ['Standard GMA 48×40 wooden pallets', 'Non-standard and custom sizes', 'Heat-treated (HT/ISPM-15) pallets', 'Plastic pallets (HDPE, PP)', 'Broken boards and stringer pieces', 'Pallet collars and extensions', 'Wooden crates and packaging'],
    process: [
      { title: 'Pickup', description: 'We bring trailers or containers and pick up on your schedule — weekly, bi-weekly, or on-demand.' },
      { title: 'Sort', description: 'Pallets graded into three tiers: repairable (Tier 1), dismantlable (Tier 2), and grind (Tier 3).' },
      { title: 'Repair or Process', description: 'Good pallets are repaired and resold. Damaged pallets are dismantled for lumber. End-of-life pallets become mulch or fuel.' },
      { title: 'Certificate', description: 'Weight documentation and Certificate of Recycling with diversion rate and processing method.' },
    ],
    whyRecycle: [
      { stat: '2B+', description: 'pallets in circulation in the US supply chain — the backbone of commercial logistics' },
      { stat: '95%', description: 'typical diversion rate for pallet waste when properly recycled through a three-tier system' },
      { stat: '~$0', description: 'cost for commercial pickup in most markets — pallets have inherent recovery value' },
      { stat: '3 lives', description: 'Average pallet is repaired and reused 3 times before end-of-life material recovery' },
    ],
    services: [
      { slug: 'pallet-recycling', name: 'Pallet Recycling', context: 'Free pickup, three-tier processing, and buyback for Grade A pallets.' },
      { slug: 'junk-removal', name: 'Junk Removal', context: 'Mixed loads including pallets, crates, and warehouse debris — we load and haul everything.' },
      { slug: 'dumpster-rental', name: 'Dumpster Rental', context: 'Roll-off containers for job sites and warehouses accumulating pallet waste.' },
    ],
    challenges: [
      { slug: 'cost-reduction', title: 'You\'re Paying to Throw Away Pallets', pain: 'Pallets have recovery value. If they\'re in your dumpster, you\'re paying disposal fees on a recyclable — and possibly revenue-generating — material.' },
      { slug: 'waste-diversion', title: 'The Lowest-Hanging Fruit', pain: 'Pallet recycling can move your diversion rate 15-20 points with zero disruption to operations. It\'s the easiest win in any waste program.' },
    ],
    industries: [
      { slug: 'logistics', name: 'Distribution & Logistics', context: 'DCs generate the highest pallet volumes. Recurring trailer swap programs keep docks clear without interrupting operations.' },
      { slug: 'retail', name: 'Retail', context: 'Receiving docks accumulate pallets daily. Scheduled pickup matches your delivery rhythm.' },
      { slug: 'manufacturing', name: 'Manufacturing', context: 'Inbound materials and outbound products both ride on pallets. We handle standard and custom sizes.' },
      { slug: 'construction', name: 'Construction', context: 'Building materials arrive on pallets that pile up at job sites. On-demand pickup for projects of any duration.' },
    ],
    cityLinks: [
      { slug: 'dallas-fort-worth', name: 'Dallas / Fort Worth', urlPrefix: 'pallet-recycling' },
      { slug: 'houston', name: 'Houston', urlPrefix: 'pallet-recycling' },
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'pallet-recycling' },
      { slug: 'atlanta', name: 'Atlanta', urlPrefix: 'pallet-recycling' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'pallet-recycling' },
      { slug: 'new-york-city', name: 'New York City', urlPrefix: 'pallet-recycling' },
      { slug: 'philadelphia', name: 'Philadelphia', urlPrefix: 'pallet-recycling' },
      { slug: 'detroit', name: 'Detroit', urlPrefix: 'pallet-recycling' },
      { slug: 'phoenix', name: 'Phoenix', urlPrefix: 'pallet-recycling' },
      { slug: 'seattle-tacoma', name: 'Seattle', urlPrefix: 'pallet-recycling' },
    ],
    faqs: [
      { q: 'Is pallet pickup really free?', a: 'For commercial volumes (typically 20+ pallets per pickup), yes — free in all service cities. Smaller quantities may have a nominal fee.' },
      { q: 'Do you buy pallets?', a: 'Grade A pallets (no broken boards, standard 48×40, good condition) qualify for buyback or revenue share. Rates depend on condition, volume, and location.' },
      { q: 'What types of pallets do you accept?', a: 'All types: GMA standard, custom sizes, heat-treated, plastic (HDPE/PP), broken boards, collars, and wooden crates. No sorting required.' },
      { q: 'How often can I schedule pickup?', a: 'Weekly, bi-weekly, monthly, or on-demand. High-volume sites get dedicated trailers on a set swap schedule.' },
      { q: 'What happens to recycled pallets?', a: 'Three-tier system: Tier 1 repaired and resold, Tier 2 dismantled for lumber recovery, Tier 3 ground into mulch, animal bedding, or biomass fuel.' },
      { q: 'Can contaminated pallets be recycled?', a: 'Pallets with standard fasteners are fine. Chemical contamination requires separate assessment — contact us to discuss.' },
      { q: 'How fast from quote to first pickup?', a: 'Most accounts live within 5-7 business days. Urgent needs often handled same-week in major metros.' },
      { q: 'Do you provide documentation?', a: 'Every pickup includes weight documentation and Certificate of Recycling with tonnage, processing method, and diversion rate.' },
    ],
    certifications: ['R2', 'ISO 14001', 'EPA compliant', 'State-licensed'],
    titleTag: 'Pallet Recycling — Free Pickup, Repair & Reuse',
    metaDescription: 'Free pallet recycling pickup for businesses. Wooden and plastic pallets. Buyback for Grade A. 95%+ diversion. 97+ cities. 817-946-5655.',
    h1: 'Pallet Recycling — Free Pickup, Repair & Reuse',
  },

  'hazardous-materials': {
    slug: 'hazardous-materials',
    name: 'Hazardous Materials',
    icon: 'warning',
    heroImage: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=1600&h=600&fit=crop',
    definition: 'Hazardous materials recycling and disposal handles regulated waste that poses a threat to human health or the environment — including batteries, fluorescent light bulbs, industrial chemicals, solvents, paint, medical waste, and mercury-containing equipment. All hazardous materials require EPA-compliant handling, manifesting, and licensed disposal.',
    headlines: {
      overview: 'Regulated Waste, Handled by the Book',
      subTypes: 'Hazardous Material Categories',
      acceptedItems: 'Regulated Materials We Handle',
      process: 'Cradle-to-Grave Documentation',
      whyRecycle: 'The Stakes Are Higher Than You Think',
      services: 'Hazardous Waste Services',
      challenges: 'What Happens When You Get It Wrong',
      industries: 'Who Generates Hazardous Waste',
      cityLinks: 'Hazardous Waste Disposal Near You',
      faq: 'Hazardous Material Questions',
      faqSubtitle: 'Regulations, manifests, and what qualifies as hazardous.',
      cta: 'Get a Hazardous Waste Quote',
      ctaSubtitle: 'Tell us what materials you need disposed of. We handle classification, manifesting, and all regulatory paperwork.',
    },
    overview: [
      'Hazardous waste isn\'t limited to chemical drums in industrial facilities. Fluorescent light bulbs contain mercury. Lithium-ion batteries cause landfill fires. Used oil and solvents contaminate groundwater. Even common office items become regulated waste when they enter the disposal stream.',
      'EPA RCRA regulations define strict handling, storage, manifesting, and disposal requirements — with penalties starting at $37,500 per day per violation. Recycling Quotes connects your business with EPA-licensed processors who handle the full regulatory chain, so you stay compliant without becoming a hazmat expert.',
    ],
    subTypes: [
      { slug: 'batteries', name: 'Batteries', description: 'Lithium-ion, lead-acid, NiCd, NiMH, and alkaline — all chemistries, any quantity' },
      { slug: 'light-bulbs', name: 'Light Bulbs & Lamps', description: 'Fluorescent tubes, CFLs, HID, mercury-vapor — all contain mercury requiring special handling' },
      { slug: 'chemicals', name: 'Chemicals & Solvents', description: 'Industrial chemicals, solvents, paint, coatings, lab chemicals, and cleaning agents' },
    ],
    acceptedItems: ['Lithium-ion batteries', 'Lead-acid batteries', 'NiCd and NiMH batteries', 'Fluorescent tubes (all sizes)', 'CFL bulbs', 'HID and mercury-vapor lamps', 'Industrial chemicals and solvents', 'Paint and coatings waste', 'Used oil and coolants', 'Medical waste and sharps', 'Laboratory chemicals', 'Mercury-containing equipment'],
    process: [
      { title: 'Waste Profiling', description: 'We classify your materials by EPA category: listed, characteristic, universal, or mixed waste.' },
      { title: 'Manifesting', description: 'We prepare hazardous waste manifests, LDR notifications, and all required regulatory paperwork.' },
      { title: 'Licensed Pickup', description: 'DOT-compliant vehicles and containers. Certified hazmat drivers with chain-of-custody documentation.' },
      { title: 'Processing', description: 'Materials treated, recycled, or disposed at EPA-permitted facilities. Batteries recycled, chemicals treated, lamps processed for mercury recovery.' },
      { title: 'Proof of Disposal', description: 'Signed manifests, certificates of disposal, and annual reporting data for EPA inspections and audits.' },
    ],
    whyRecycle: [
      { stat: '$37,500/day', description: 'per violation — the minimum EPA penalty for improper hazardous waste handling under RCRA' },
      { stat: '3B lbs', description: 'of batteries discarded annually in the US — many containing toxic heavy metals and fire-risk lithium' },
      { stat: '600M', description: 'fluorescent lamps used annually in the US — each containing mercury that requires special disposal' },
      { stat: 'Criminal', description: 'liability possible for knowing violations of RCRA — not just fines, but potential imprisonment' },
    ],
    services: [
      { slug: 'hazardous-waste-disposal', name: 'Hazardous Waste Disposal', context: 'Full-service hazardous waste management with profiling, manifesting, pickup, and licensed disposal.' },
      { slug: 'business-recycling-programs', name: 'Business Recycling Programs', context: 'Hazmat streams integrated into a comprehensive recycling program with consolidated reporting.' },
      { slug: 'collection-events', name: 'Collection Events', context: 'Community and corporate hazardous waste collection days with permitted handling and processing.' },
    ],
    challenges: [
      { slug: 'hazardous-waste', title: 'Fines That Can Bankrupt a Business', pain: 'EPA enforcement is aggressive and penalties compound daily. Proper handling with documented compliance is your only protection.' },
      { slug: 'esg-reporting', title: 'Audit-Proof Documentation', pain: 'Environmental audits require complete hazardous waste records. Signed manifests and certificates of disposal are your proof.' },
    ],
    industries: [
      { slug: 'healthcare', name: 'Healthcare', context: 'Medical waste, pharmaceutical disposal, lab chemicals — all regulated under RCRA, OSHA, and state medical waste rules.' },
      { slug: 'manufacturing', name: 'Manufacturing', context: 'Solvents, cutting fluids, paint waste, and process chemicals generated in production operations.' },
      { slug: 'construction', name: 'Construction', context: 'Lead paint, asbestos, fluorescent fixtures, and chemical waste from demolition and renovation.' },
      { slug: 'education', name: 'Education & Government', context: 'Lab chemicals, mercury thermometers, fluorescent tubes, and universal waste from campus facilities.' },
    ],
    cityLinks: [
      { slug: 'houston', name: 'Houston', urlPrefix: 'hazardous-waste-disposal' },
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'hazardous-waste-disposal' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'hazardous-waste-disposal' },
      { slug: 'new-york-city', name: 'New York City', urlPrefix: 'hazardous-waste-disposal' },
      { slug: 'boston', name: 'Boston', urlPrefix: 'hazardous-waste-disposal' },
      { slug: 'dallas-fort-worth', name: 'Dallas / Fort Worth', urlPrefix: 'hazardous-waste-disposal' },
      { slug: 'philadelphia', name: 'Philadelphia', urlPrefix: 'hazardous-waste-disposal' },
      { slug: 'detroit', name: 'Detroit', urlPrefix: 'hazardous-waste-disposal' },
      { slug: 'atlanta', name: 'Atlanta', urlPrefix: 'hazardous-waste-disposal' },
      { slug: 'toronto-mississauga', name: 'Toronto', urlPrefix: 'hazardous-waste-disposal' },
    ],
    faqs: [
      { q: 'What qualifies as hazardous waste?', a: 'Under EPA RCRA, waste is hazardous if it\'s on the F/K/P/U lists or exhibits ignitability, corrosivity, reactivity, or toxicity. Common examples: batteries, fluorescent lamps, solvents, paint, and certain cleaning chemicals.' },
      { q: 'What is universal waste?', a: 'A subset of hazardous waste with simplified rules: batteries, lamps, mercury equipment, and pesticides. Easier to handle than fully regulated hazmat but still requires licensed disposal.' },
      { q: 'Do you prepare the manifests?', a: 'Yes. We handle all regulatory paperwork including hazardous waste manifests (EPA Form 8700-22), LDR notifications, and generator certifications.' },
      { q: 'How long can I store hazardous waste?', a: 'Depends on generator status: VSQGs have no time limit (1,000 kg cap). SQGs get 270 days. LQGs get 90 days. Exceeding limits triggers permit requirements.' },
      { q: 'Can you handle pharmaceutical waste?', a: 'Yes — under DEA reverse distribution rules and EPA pharmaceutical waste regulations. Includes both hazardous and non-hazardous pharmaceutical waste.' },
      { q: 'What about batteries?', a: 'All chemistries: lithium-ion, lead-acid, NiCd, NiMH, alkaline. Batteries are recycled for metal recovery. Lithium batteries require special DOT packaging for transport.' },
      { q: 'What documentation do I receive?', a: 'Signed manifests with TSDF return copies, certificates of disposal, annual quantity reports, and waste profile sheets.' },
      { q: 'What if we get an EPA inspection?', a: 'If waste is properly profiled, manifested, and disposed through licensed facilities, you have a complete audit trail. We provide organized documentation packages.' },
    ],
    certifications: ['EPA RCRA', 'DOT certified', 'State hazmat permits', 'OSHA compliant'],
    titleTag: 'Hazardous Materials Recycling & Disposal — EPA Licensed',
    metaDescription: 'EPA-licensed hazardous waste disposal for batteries, chemicals, light bulbs, and medical waste. Manifests included. 97+ cities. 817-946-5655.',
    h1: 'Hazardous Materials — EPA-Licensed Disposal & Recycling',
  },

  'textiles': {
    slug: 'textiles',
    name: 'Textiles',
    icon: 'checkroom',
    heroImage: 'https://images.unsplash.com/photo-1558171813-01342daa353e?w=1600&h=600&fit=crop',
    definition: 'Textile recycling recovers clothing, fabric, and industrial textile waste for reuse, fiber reclamation, or downcycling into industrial rags, insulation, and padding. The US generates over 17 million tons of textile waste annually — of which 66% goes to landfill.',
    headlines: {
      overview: '17 Million Tons of Fabric Waste Per Year',
      acceptedItems: 'Textiles We Accept',
      process: 'Sort, Grade, Recycle',
      whyRecycle: 'The Cost of Textile Waste',
      services: 'Textile Recycling Services',
      challenges: 'Fast Fashion Meets Sustainability Goals',
      industries: 'Who Generates Textile Waste',
      cityLinks: 'Textile Recycling in Your City',
      faq: 'Textile Recycling Questions',
      faqSubtitle: 'What\'s accepted, what gets donated, and what becomes rags.',
      cta: 'Get a Textile Recycling Quote',
      ctaSubtitle: 'Tell us what you have — retail overstock, manufacturing cutoffs, or post-consumer returns. We\'ll find the best outlet.',
    },
    overview: [
      'Textile waste is the fastest-growing segment of the municipal waste stream, driven by fast fashion and shortened product lifecycles. For commercial operations — retailers, manufacturers, hospitality, and uniforms — textile waste often goes straight to landfill because few recycling programs handle it.',
      'Recycling Quotes provides commercial textile recycling that prioritizes reuse first (usable items go to charity or resale), then fiber reclamation (clean textiles become insulation or industrial wipers), and finally energy recovery for non-recyclable materials.',
    ],
    acceptedItems: ['Clothing and apparel (all conditions)', 'Shoes and accessories', 'Retail overstock and returns', 'Manufacturing cutoffs and remnants', 'Uniforms and workwear', 'Linens, towels, and bedding', 'Curtains and upholstery fabric', 'Industrial wiping rags'],
    process: [
      { title: 'Collection', description: 'Bins, gaylords, or scheduled pickup — sized to your volume and placed where textile waste accumulates.' },
      { title: 'Sorting', description: 'Items graded: reusable (donation/resale), recyclable (fiber reclamation), and non-recyclable (energy recovery).' },
      { title: 'Processing', description: 'Reusable items go to charity. Recyclable textiles become rags, insulation, or fiber. Nothing goes to landfill.' },
      { title: 'Documentation', description: 'Weight documentation, diversion report, and donation receipts for tax purposes.' },
    ],
    whyRecycle: [
      { stat: '17M tons', description: 'of textile waste generated annually in the US — growing faster than any other waste category' },
      { stat: '66%', description: 'of textile waste goes to landfill — where synthetic fabrics persist for 200+ years' },
      { stat: '700 gallons', description: 'of water needed to produce a single cotton t-shirt — recycling conserves these resources' },
      { stat: '10%', description: 'of global carbon emissions come from the fashion industry — recycling reduces the lifecycle footprint' },
    ],
    services: [
      { slug: 'business-recycling-programs', name: 'Business Recycling Programs', context: 'Textile recycling as part of a multi-stream commercial recycling program.' },
      { slug: 'take-back-programs', name: 'Take Back Programs', context: 'Consumer-facing clothing collection programs for retailers and apparel brands.' },
      { slug: 'junk-removal', name: 'Junk Removal', context: 'Bulk textile removal from warehouses, stores, and storage units.' },
    ],
    challenges: [
      { slug: 'waste-diversion', title: 'The Fastest-Growing Waste Stream', pain: 'Textile waste is growing faster than any other category. Adding a textile stream to your recycling program captures material that would otherwise go straight to landfill.' },
      { slug: 'esg-reporting', title: 'Circular Economy in Action', pain: 'Textile recycling is a visible demonstration of circular economy principles — great for sustainability reports and brand messaging.' },
    ],
    industries: [
      { slug: 'retail', name: 'Retail', context: 'Unsold inventory, damaged goods, returns, and hangers from apparel retail. Take-back programs drive foot traffic and brand loyalty.' },
      { slug: 'hospitality', name: 'Hospitality', context: 'Hotels and resorts cycle through linens, towels, and uniforms. Worn items are recycled into industrial wipers.' },
      { slug: 'manufacturing', name: 'Manufacturing', context: 'Cutting room waste, fabric remnants, and rejected textiles from apparel and upholstery manufacturing.' },
    ],
    cityLinks: [
      { slug: 'new-york-city', name: 'New York City', urlPrefix: 'textiles-recycling' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'textiles-recycling' },
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'textiles-recycling' },
      { slug: 'dallas-fort-worth', name: 'Dallas / Fort Worth', urlPrefix: 'textiles-recycling' },
      { slug: 'atlanta', name: 'Atlanta', urlPrefix: 'textiles-recycling' },
      { slug: 'houston', name: 'Houston', urlPrefix: 'textiles-recycling' },
      { slug: 'miami-fort-lauderdale', name: 'Miami', urlPrefix: 'textiles-recycling' },
      { slug: 'phoenix', name: 'Phoenix', urlPrefix: 'textiles-recycling' },
    ],
    faqs: [
      { q: 'What condition do textiles need to be in?', a: 'We accept all conditions — wearable, stained, torn, or damaged. Usable items are donated or resold. Damaged textiles are recycled into industrial wipers, insulation, or fiber.' },
      { q: 'Do you provide donation receipts?', a: 'Yes. Items donated through our charity partners come with a receipt for tax deduction purposes.' },
      { q: 'What happens to non-wearable textiles?', a: 'Clean textiles become industrial wipers or insulation. Fiber-quality materials are shredded and processed into new padding or fill. Synthetic fabrics may go to waste-to-energy.' },
      { q: 'Do you handle retail overstock?', a: 'Yes. We manage overstock, returns, and end-of-season inventory. Usable items are resold through discount channels or donated. Branded items can be de-labeled before resale.' },
      { q: 'What\'s the minimum volume?', a: 'For scheduled pickup: 500+ lbs. For one-time cleanouts, we handle any volume. Smaller ongoing volumes can join a multi-stream recycling program.' },
      { q: 'Can you handle uniforms and workwear?', a: 'Yes. Branded uniforms are de-branded before recycling or donation. We provide documentation for brand-protection compliance.' },
      { q: 'Is there revenue from textile recycling?', a: 'Clean, sorted textiles in good condition may qualify for commodity value. Most commercial textile recycling is provided at no cost or nominal cost depending on volume and condition.' },
      { q: 'Do you handle shoes?', a: 'Yes. Wearable shoes are donated. Non-wearable shoes are recycled — rubber soles are separated from uppers for material-specific processing.' },
    ],
    certifications: ['ISO 14001', 'EPA compliant', 'Charity partnerships'],
    titleTag: 'Textile Recycling — Clothing, Fabric & Industrial Textiles',
    metaDescription: 'Commercial textile recycling for clothing, fabric, uniforms, and linens. Reuse, fiber reclamation, and certified disposal. 97+ cities. 817-946-5655.',
    h1: 'Textile Recycling — Clothing, Fabric & Industrial Textiles',
  },

  'organics': {
    slug: 'organics',
    name: 'Organics',
    icon: 'compost',
    heroImage: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=1600&h=600&fit=crop',
    definition: 'Organic waste recycling diverts food waste, yard waste, and compostable materials from landfill through composting, anaerobic digestion, or animal feed programs. Food waste is the single largest category of material sent to landfill in the US — generating methane, a greenhouse gas 80x more potent than CO2.',
    headlines: {
      overview: 'The Biggest Thing in Your Dumpster Shouldn\'t Be There',
      acceptedItems: 'Organic Materials We Divert',
      process: 'From Waste to Compost or Energy',
      whyRecycle: 'Food Waste Is a Climate Problem',
      services: 'Organics Recycling Services',
      challenges: 'Regulations Are Catching Up',
      industries: 'Top Organic Waste Generators',
      cityLinks: 'Organics Recycling in Your City',
      faq: 'Organics Recycling Questions',
      faqSubtitle: 'What\'s accepted, composting vs anaerobic digestion, and state mandates.',
      cta: 'Get an Organics Recycling Quote',
      ctaSubtitle: 'Tell us about your food waste and we\'ll design a diversion program that meets your goals and any regulatory requirements.',
    },
    overview: [
      'Food waste makes up roughly 24% of material sent to US landfills — more than any other single material category. When food decomposes in a landfill without oxygen, it generates methane, a greenhouse gas roughly 80 times more potent than CO2 over a 20-year period. Diverting organics isn\'t just about waste — it\'s climate action.',
      'Recycling Quotes provides organic waste collection programs that route food waste, yard waste, and compostable materials to composting facilities, anaerobic digesters, or animal feed programs. For commercial food operations generating consistent volumes, we provide source-separated collection with proper containers and pickup frequencies.',
    ],
    acceptedItems: ['Pre-consumer food waste (prep scraps, trim)', 'Post-consumer food waste (plate scrapings)', 'Expired food and beverages', 'Bakery and dairy waste', 'Yard waste and landscape trimmings', 'Compostable serviceware (BPI certified)', 'Coffee grounds and filters', 'Soiled paper and cardboard (food-contaminated)'],
    process: [
      { title: 'Assessment', description: 'We evaluate your organic waste volume, type (pre-consumer vs post-consumer), and available space for collection containers.' },
      { title: 'Collection Setup', description: 'Toters, carts, or dumpsters placed in kitchens, prep areas, and loading docks. Staff training on what goes in.' },
      { title: 'Pickup', description: 'Scheduled service matched to your generation rate — daily for high-volume kitchens, 2-3x weekly for smaller operations.' },
      { title: 'Processing', description: 'Organics routed to composting facilities or anaerobic digesters depending on your local infrastructure.' },
    ],
    whyRecycle: [
      { stat: '24%', description: 'of US landfill waste is food — the single largest material category in municipal solid waste' },
      { stat: '80x', description: 'methane is more potent as a greenhouse gas than CO2 over 20 years — landfilled food generates massive methane' },
      { stat: '35%', description: 'of food produced in the US is never eaten — representing $400+ billion in wasted resources annually' },
      { stat: '13 states', description: 'have passed or proposed organic waste bans or diversion mandates for commercial generators' },
    ],
    services: [
      { slug: 'business-recycling-programs', name: 'Business Recycling Programs', context: 'Organics collection as part of a comprehensive multi-stream program with diversion tracking.' },
      { slug: 'waste-audits-consulting', name: 'Waste Audits & Consulting', context: 'Food waste audits identify diversion opportunities and quantify potential cost savings.' },
      { slug: 'dumpster-rental', name: 'Dumpster Rental', context: 'Organics-specific containers for large-volume food waste generators.' },
    ],
    challenges: [
      { slug: 'waste-diversion', title: 'Food Is the Biggest Diversion Opportunity', pain: 'Diverting organics alone can improve your total waste diversion rate by 20-30 points. It\'s the single biggest opportunity in most waste streams.' },
      { slug: 'esg-reporting', title: 'Climate Impact You Can Measure', pain: 'Organic waste diversion has the highest carbon impact per ton diverted. Methane avoidance data is powerful in ESG reports.' },
    ],
    industries: [
      { slug: 'food-services', name: 'Food Services', context: 'Restaurants, cafeterias, and catering generate the most concentrated food waste. Daily pickup keeps kitchens clean and compliant.' },
      { slug: 'hospitality', name: 'Hospitality', context: 'Hotels and resorts with restaurants, banquet halls, and room service generate significant organic waste volumes.' },
      { slug: 'retail', name: 'Retail', context: 'Grocery stores and supermarkets generate expired produce, bakery, deli, and dairy waste daily.' },
      { slug: 'education', name: 'Education & Government', context: 'School cafeterias, university dining halls, and government facilities with food service operations.' },
    ],
    cityLinks: [
      { slug: 'san-francisco-oakland', name: 'San Francisco', urlPrefix: 'organics-recycling' },
      { slug: 'seattle-tacoma', name: 'Seattle', urlPrefix: 'organics-recycling' },
      { slug: 'new-york-city', name: 'New York City', urlPrefix: 'organics-recycling' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'organics-recycling' },
      { slug: 'portland-vancouver', name: 'Portland', urlPrefix: 'organics-recycling' },
      { slug: 'boston', name: 'Boston', urlPrefix: 'organics-recycling' },
      { slug: 'denver', name: 'Denver', urlPrefix: 'organics-recycling' },
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'organics-recycling' },
    ],
    faqs: [
      { q: 'What types of organic waste do you accept?', a: 'Pre-consumer food waste (prep scraps, trim), post-consumer food waste (plate scrapings), expired food, yard waste, BPI-certified compostable serviceware, coffee grounds, and food-contaminated paper/cardboard.' },
      { q: 'What\'s the difference between composting and anaerobic digestion?', a: 'Composting decomposes organics aerobically (with oxygen) into soil amendment. Anaerobic digestion breaks down organics without oxygen, producing biogas (renewable energy) and digestate. We route to whichever facility is available in your area.' },
      { q: 'Does my state require organic waste diversion?', a: 'As of 2025, 13+ states have passed or proposed organic waste mandates for commercial generators. California (SB 1383), Vermont, Connecticut, Massachusetts, and New York are among the strictest. Contact us for your state\'s requirements.' },
      { q: 'How do you prevent odor and pest issues?', a: 'Proper containers with tight-fitting lids, appropriate collection frequency (daily for high-volume kitchens), and staff training on what goes in. We size the program to prevent accumulation and odor.' },
      { q: 'Can compostable packaging go in?', a: 'BPI-certified compostable serviceware is accepted at most commercial composting facilities. Non-certified "eco-friendly" packaging often cannot be composted — check for the BPI logo.' },
      { q: 'What documentation do I receive?', a: 'Weight tickets, monthly diversion reports, and methane avoidance calculations. Annual data formatted for SB 1383 compliance (CA) and other state reporting requirements.' },
      { q: 'What\'s the minimum volume?', a: 'For dedicated organics pickup: one 64-gallon toter per week minimum. Smaller volumes can often be handled through municipal composting programs where available.' },
      { q: 'Is there a cost savings vs landfill?', a: 'In many markets, organics diversion is cost-neutral or cheaper than landfill disposal — especially in states with organic waste bans where landfill tipping fees include surcharges for organic content.' },
    ],
    certifications: ['STA certified compost', 'EPA compliant', 'State organic waste permits'],
    titleTag: 'Organic Waste Recycling — Food Waste & Composting Programs',
    metaDescription: 'Commercial food waste and organic recycling programs. Composting, anaerobic digestion, and compliance with state mandates. 97+ cities. 817-946-5655.',
    h1: 'Organic Waste Recycling — Food Waste & Composting',
  },

  'vehicles': {
    slug: 'vehicles',
    name: 'Vehicles',
    icon: 'directions_car',
    heroImage: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1600&h=600&fit=crop',
    definition: 'Vehicle recycling (auto recycling) is the process of dismantling end-of-life vehicles to recover reusable parts, scrap metal, fluids, and other materials. Approximately 12-15 million vehicles reach end-of-life annually in the US, with a recycling rate above 95% by weight — making automotive the most recycled consumer product.',
    headlines: {
      overview: 'The Most Recycled Consumer Product in America',
      acceptedItems: 'Vehicles and Parts We Accept',
      process: 'From End-of-Life to Recovered Materials',
      whyRecycle: 'Vehicles Are 95% Recyclable',
      services: 'Vehicle Recycling Services',
      challenges: 'Compliance and Environmental Liability',
      industries: 'Who Retires Vehicles',
      cityLinks: 'Vehicle Recycling in Your City',
      faq: 'Vehicle Recycling Questions',
      faqSubtitle: 'Titles, fluids, catalytic converters, and what your vehicle is worth.',
      cta: 'Get a Vehicle Recycling Quote',
      ctaSubtitle: 'Tell us about your vehicle or fleet and we\'ll provide a quote for pickup, dismantling, and certified recycling.',
    },
    overview: [
      'Vehicles are the most recycled consumer product in the United States — over 95% of a vehicle by weight can be recovered and recycled. Steel, aluminum, copper, platinum group metals (from catalytic converters), glass, rubber, and plastics all have established recycling markets.',
      'For businesses managing fleet vehicles, dealership trade-ins, or insurance write-offs, proper end-of-life vehicle processing ensures environmental compliance (fluid drainage, refrigerant recovery, airbag deployment), recovers maximum value from parts and materials, and provides clean title documentation.',
    ],
    acceptedItems: ['Cars and trucks (all makes, models, conditions)', 'Fleet vehicles and commercial trucks', 'Motorcycles and ATVs', 'RVs and campers', 'Boats (trailered)', 'Heavy equipment and forklifts', 'Auto parts: engines, transmissions, body panels', 'Catalytic converters (with documentation)', 'Tires and wheels', 'Batteries (automotive)'],
    process: [
      { title: 'Assessment', description: 'We evaluate your vehicle(s) — make, model, condition, and title status to determine the best recovery path.' },
      { title: 'Pickup', description: 'We tow or haul vehicles from your location. Fleet pickups coordinated for minimal operational disruption.' },
      { title: 'Dismantling', description: 'Fluids drained and recycled. Reusable parts pulled. Hazardous components (refrigerant, airbags, mercury switches) safely removed.' },
      { title: 'Crushing & Shredding', description: 'Remaining hulk processed through industrial shredders. Metals separated by type for resale to mills.' },
      { title: 'Documentation', description: 'Title processing, Certificate of Recycling, and weight documentation for your fleet management or insurance records.' },
    ],
    whyRecycle: [
      { stat: '95%+', description: 'of a vehicle by weight can be recovered and recycled — steel, aluminum, copper, and precious metals' },
      { stat: '12-15M', description: 'vehicles reach end-of-life annually in the US — a massive source of recyclable materials' },
      { stat: '14M tons', description: 'of recycled steel from vehicles re-enters manufacturing each year' },
      { stat: '$32B', description: 'annual contribution of the auto recycling industry to the US economy' },
    ],
    services: [
      { slug: 'scrap-metal-recycling', name: 'Scrap Metal Recycling', context: 'Vehicle hulks and auto parts processed through our metal recycling network.' },
      { slug: 'hazardous-waste-disposal', name: 'Hazardous Waste Disposal', context: 'Fluids, refrigerants, batteries, and mercury switches handled through licensed hazmat channels.' },
      { slug: 'junk-removal', name: 'Junk Removal', context: 'Full-service hauling for non-running vehicles and auto parts from your property.' },
    ],
    challenges: [
      { slug: 'hazardous-waste', title: 'Vehicles Contain Regulated Materials', pain: 'Motor oil, coolant, refrigerant, lead-acid batteries, and mercury switches all require proper handling. Improper disposal creates environmental liability.' },
      { slug: 'cost-reduction', title: 'End-of-Life Vehicles Still Have Value', pain: 'Parts, metals, and catalytic converters all have market value. A proper recycling process recovers maximum value instead of paying for disposal.' },
    ],
    industries: [
      { slug: 'automotive', name: 'Automotive', context: 'Dealerships, body shops, and fleet operators retire vehicles regularly. We coordinate volume processing with title management.' },
      { slug: 'logistics', name: 'Distribution & Logistics', context: 'Fleet vehicles, delivery vans, and trucks reaching end-of-life. We handle full fleet disposition with documentation.' },
      { slug: 'construction', name: 'Construction', context: 'Heavy equipment, site vehicles, and fleet trucks. We process everything from pickup trucks to excavators.' },
    ],
    cityLinks: [
      { slug: 'houston', name: 'Houston', urlPrefix: 'vehicle-recycling' },
      { slug: 'detroit', name: 'Detroit', urlPrefix: 'vehicle-recycling' },
      { slug: 'dallas-fort-worth', name: 'Dallas / Fort Worth', urlPrefix: 'vehicle-recycling' },
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'vehicle-recycling' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'vehicle-recycling' },
      { slug: 'atlanta', name: 'Atlanta', urlPrefix: 'vehicle-recycling' },
      { slug: 'phoenix', name: 'Phoenix', urlPrefix: 'vehicle-recycling' },
      { slug: 'philadelphia', name: 'Philadelphia', urlPrefix: 'vehicle-recycling' },
    ],
    faqs: [
      { q: 'Do I need a title to recycle a vehicle?', a: 'Ideally yes. A clean title streamlines processing. For vehicles without titles, we can work with your state\'s DMV processes — abandoned vehicle affidavits, bonded titles, or mechanic\'s liens depending on your jurisdiction.' },
      { q: 'How much is my vehicle worth for recycling?', a: 'Value depends on weight (primarily steel), catalytic converter type, and reusable parts. A typical sedan yields $200-$500 in scrap value. Vehicles with high-value catalytic converters or salvageable parts can be worth more.' },
      { q: 'Do you pick up non-running vehicles?', a: 'Yes. We provide towing for non-running vehicles at no additional cost in most markets for vehicles with sufficient scrap value.' },
      { q: 'What happens to the fluids?', a: 'All fluids (oil, coolant, transmission fluid, brake fluid, refrigerant) are drained and recycled through licensed processors before the vehicle is shredded. This is an EPA requirement.' },
      { q: 'Can you handle a fleet disposition?', a: 'Yes. We manage multi-vehicle fleet dispositions with coordinated pickup schedules, title processing, and consolidated reporting. Common for fleet operators retiring 10-100+ vehicles.' },
      { q: 'What about catalytic converter theft documentation?', a: 'We require valid ID and vehicle documentation for all catalytic converter transactions, in compliance with state theft-prevention laws. We can provide documentation for insurance claims.' },
      { q: 'Do you recycle heavy equipment?', a: 'Yes — forklifts, excavators, loaders, and other heavy equipment. These are dismantled for parts and metal recovery, with proper handling of hydraulic fluids and other regulated materials.' },
      { q: 'What documentation do I receive?', a: 'Certificate of Recycling, title receipt, weight documentation, and for fleets, a consolidated disposition report with per-vehicle tracking.' },
    ],
    certifications: ['State auto dismantler license', 'EPA compliant', 'Licensed fluid recycling'],
    titleTag: 'Vehicle Recycling — Cars, Trucks, Fleet & Auto Parts',
    metaDescription: 'Recycle end-of-life vehicles with certified dismantling and 95%+ material recovery. Cars, trucks, fleet vehicles. Pickup included. 817-946-5655.',
    h1: 'Vehicle Recycling — Cars, Trucks, Fleet & Auto Parts',
  },

  'junk': {
    slug: 'junk',
    name: 'Junk & Bulky Items',
    icon: 'delete',
    heroImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1600&h=600&fit=crop',
    definition: 'Junk and bulky item recycling handles oversized, mixed, or hard-to-categorize waste — furniture, appliances, mattresses, exercise equipment, and general clutter — through full-service removal with maximum diversion through donation, recycling, and responsible disposal.',
    headlines: {
      overview: 'Everything That Doesn\'t Fit in a Bin',
      acceptedItems: 'What We Haul Away',
      process: 'Point at It. We Do the Rest.',
      whyRecycle: 'Not Everything Has to Be Trashed',
      services: 'Junk Hauling Services',
      challenges: 'When You Need It Gone Now',
      industries: 'Who Needs Junk Removal',
      cityLinks: 'Junk Removal in Your City',
      faq: 'Junk & Bulky Item Questions',
      faqSubtitle: 'What we take, what it costs, and how fast we can get there.',
      cta: 'Schedule Junk Removal',
      ctaSubtitle: 'Tell us what needs to go and when. We send a crew, load everything, and leave the space clean.',
    },
    overview: [
      'Some waste doesn\'t fit into a neat recycling category. Old office furniture, broken appliances, mattresses, exercise equipment, and general accumulated clutter all need to go somewhere — and a standard recycling bin isn\'t the answer.',
      'Our junk removal service sends a crew to your location, loads everything, and sorts it afterward for maximum diversion. Usable items go to local charities. Metals, electronics, and wood are recycled. Only truly non-recyclable material goes to landfill. You get a clean space and a diversion report showing where everything went.',
    ],
    acceptedItems: ['Office furniture (desks, chairs, cubicles, filing cabinets)', 'Residential furniture (couches, mattresses, tables, dressers)', 'Appliances (refrigerators, washers, dryers, dishwashers)', 'Electronics and IT equipment', 'Exercise equipment (treadmills, bikes, weights)', 'Hot tubs, swing sets, and outdoor structures', 'Construction debris and renovation waste', 'General clutter and storage cleanouts'],
    process: [
      { title: 'Book', description: 'Call or book online with a description of what needs to go. We give you a time window — often same-day.' },
      { title: 'Quote', description: 'Our crew arrives, surveys the items, and gives you an exact price before we touch anything.' },
      { title: 'Load', description: 'Approve the price and we load everything. We carry, lift, and haul — you don\'t touch a thing.' },
      { title: 'Divert', description: 'Items sorted post-pickup: donate, recycle, or dispose. You get a summary of where everything went.' },
    ],
    whyRecycle: [
      { stat: '60-70%', description: 'of items we haul can be donated or recycled — only 30-40% actually needs to be landfilled' },
      { stat: 'Same day', description: 'service available in most major metros for requests placed before noon' },
      { stat: '$0 donated', description: 'cost to you for usable items we donate — plus a donation receipt for your tax records' },
      { stat: '2-person', description: 'crew handles everything — loading, carrying, hauling, and post-removal cleanup included' },
    ],
    services: [
      { slug: 'junk-removal', name: 'Junk Removal', context: 'Full-service hauling — we load, carry, and haul everything. You point, we handle the rest.' },
      { slug: 'dumpster-rental', name: 'Dumpster Rental', context: 'When you want to load it yourself on your own timeline — roll-off containers for any project.' },
      { slug: 'business-recycling-programs', name: 'Business Recycling Programs', context: 'Ongoing junk removal as part of a managed program for property management and facilities.' },
    ],
    challenges: [
      { slug: 'cost-reduction', title: 'Faster and Cheaper Than You Think', pain: 'Having employees move junk costs more than hiring pros when you factor in time, workers comp risk, truck rental, and dump fees.' },
      { slug: 'waste-diversion', title: 'Not Everything Should Be Trashed', pain: 'That old desk could furnish a nonprofit. Those appliances could be refurbished. We sort for maximum diversion before anything goes to landfill.' },
    ],
    industries: [
      { slug: 'property-management', name: 'Property Management', context: 'Unit turns, tenant cleanouts, and bulk item removal on tight leasing timelines.' },
      { slug: 'retail', name: 'Retail', context: 'Fixture disposal, display removal, and back-of-store cleanouts during remodels.' },
      { slug: 'construction', name: 'Construction', context: 'Post-construction cleanup, debris removal, and final broom-clean before project handover.' },
    ],
    cityLinks: [
      { slug: 'chicago', name: 'Chicago', urlPrefix: 'junk-removal' },
      { slug: 'atlanta', name: 'Atlanta', urlPrefix: 'junk-removal' },
      { slug: 'los-angeles', name: 'Los Angeles', urlPrefix: 'junk-removal' },
      { slug: 'dallas-fort-worth', name: 'Dallas / Fort Worth', urlPrefix: 'junk-removal' },
      { slug: 'houston', name: 'Houston', urlPrefix: 'junk-removal' },
      { slug: 'miami-fort-lauderdale', name: 'Miami', urlPrefix: 'junk-removal' },
      { slug: 'phoenix', name: 'Phoenix', urlPrefix: 'junk-removal' },
      { slug: 'charlotte', name: 'Charlotte', urlPrefix: 'junk-removal' },
    ],
    faqs: [
      { q: 'How is junk removal priced?', a: 'Volume-based — how much space items take in our truck. We quote exact prices onsite before starting. Most residential jobs: $200-$800. Commercial cleanouts quoted by project scope.' },
      { q: 'Can you come same-day?', a: 'In most major metros, yes for requests before noon. Next-day available almost everywhere. Large commercial jobs typically scheduled 2-3 days out.' },
      { q: 'What can\'t you take?', a: 'Hazardous materials (paint, chemicals, asbestos) and medical waste require specialized disposal. Everything else — including appliances, mattresses, and electronics — we handle.' },
      { q: 'Do you recycle or just dump everything?', a: 'We sort everything post-pickup. Usable items go to charity. Metals, electronics, and cardboard are recycled. Only non-recyclable material goes to landfill. You get a diversion summary.' },
      { q: 'Do I need to be there?', a: 'Someone needs to be present to approve the quote and provide access. For ongoing commercial accounts, unattended pickups with pre-authorized access and pricing are available.' },
      { q: 'Can you handle heavy items?', a: 'Yes — pianos, safes, hot tubs, commercial appliances, exercise equipment. For extremely heavy items, let us know in advance.' },
      { q: 'Do you provide donation receipts?', a: 'Yes. Items donated through our charity partners come with a receipt with estimated value for tax deductions.' },
      { q: 'How many people come?', a: 'Standard: 2-person crew. Large commercial cleanouts: 4-6 people with multiple trucks. We scale to the job.' },
    ],
    certifications: ['Insured', 'Licensed hauler', 'EPA compliant'],
    titleTag: 'Junk & Bulky Item Removal — Same-Day Service',
    metaDescription: 'Full-service junk removal for furniture, appliances, electronics, and general clutter. Same-day available. We donate and recycle. 97+ cities. 817-946-5655.',
    h1: 'Junk & Bulky Item Removal — Same-Day Service',
  },
};
